#!/usr/bin/env python3
"""Generate `packages/zip/src/cp437.mfb` from Python's own CP437 codec.

The table is transcribed rather than typed. APPNOTE.TXT Appendix D defines the
encoding zip uses for names without general-purpose flag bit 11, and Python
ships that same mapping as the `cp437` codec, so generating the table from the
codec removes the one failure mode a hand-typed 256-entry table has: a single
wrong character that nothing notices until an archive with that byte in a name
shows up.

Run from the repository root:

    python3 packages/zip/oracle/cp437_table.py
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(HERE), "src", "cp437.mfb")

HEADER = """\
' ---------------------------------------------------------------------------
' GENERATED by packages/zip/oracle/cp437_table.py -- do not edit by hand.
'
' Code page 437 -- the encoding a zip entry name uses when general-purpose flag
' bit 11 is clear (APPNOTE.TXT Appendix D, and §4.4.4 for the flag).
'
' This package carries its own table because `encoding::Codepage` has no CP437
' member: `mfb man encoding types` lists Ibm866, the Iso8859 family and the
' Windows family only. Decoding such a name as UTF-8 instead would turn every
' archive written by a DOS-era or Windows-default zip tool into either a
' mangled name or a spurious "invalid UTF-8" refusal.
'
' The table is 256 Unicode code points, one per byte value, in order from 0x00.
' Bytes 0x00..0x7F are US-ASCII and map to themselves; the high half is the
' CP437 repertoire. Decoding maps each byte through the table and hands the
' whole list to `strings::fromScalars`, so a name costs one string build rather
' than one concatenation per character.
'
' Regenerate with:  python3 packages/zip/oracle/cp437_table.py
' ---------------------------------------------------------------------------

IMPORT collections
IMPORT strings

' The Unicode code point for each CP437 byte, indexed by the byte's value.
PRIVATE FUNC codePoints() AS List OF Integer
  RETURN [ _
"""

FOOTER = """\
  ]
END FUNC

' Decode `bytes` as CP437 into a String.
'
' Every byte has a character in CP437 -- it is a complete single-byte encoding
' with no undefined positions -- so this never fails, which is precisely why the
' format uses it as the fallback for a name that is not declared UTF-8.
EXPORT FUNC cp437Decode(bytes AS List OF Byte) AS String
  LET table AS List OF Integer = codePoints()
  MUT scalars AS List OF Scalar = []
  FOR EACH b IN bytes
    scalars = collections::append(scalars, toScalar(collections::get(table, toInt(b))))
  NEXT
  RETURN strings::fromScalars(scalars)
END FUNC
"""


def main():
    rows = []
    for value in range(0x100):
        ch = bytes([value]).decode("cp437")
        sep = "," if value != 0xFF else ""
        rows.append("    %d%s" % (ord(ch), sep))
    # Eight code points per line keeps the table compact and diffable.
    lines = []
    for start in range(0, 0x100, 8):
        group = []
        for value in range(start, start + 8):
            ch = bytes([value]).decode("cp437")
            sep = "," if value != 0xFF else ""
            group.append("%d%s" % (ord(ch), sep))
        # Every line continues, including the last: the closing bracket is on
        # its own line in FOOTER.
        cont = " _"
        lines.append("    " + " ".join(group) + cont)
    with open(OUT, "w") as fh:
        fh.write(HEADER + "\n".join(lines) + "\n" + FOOTER)
    print("wrote %s (256 code points)" % OUT)


if __name__ == "__main__":
    sys.exit(main())
