use super::{Rule, Severity};

pub(super) const RULES: &[Rule] = &[
    Rule {
        code: "2-200-0001",
        name: "PROJECT_JSON_MISSING",
        severity: Severity::Error,
        message: "project.json is required",
    },
    Rule {
        code: "2-200-0002",
        name: "PROJECT_JSON_READ_FAILED",
        severity: Severity::Error,
        message: "project.json could not be read",
    },
    Rule {
        code: "2-200-0003",
        name: "PROJECT_JSON_PARSE_FAILED",
        severity: Severity::Error,
        message: "project.json is not valid JSON",
    },
    Rule {
        code: "2-200-0004",
        name: "PROJECT_JSON_ROOT_TYPE",
        severity: Severity::Error,
        message: "project.json must contain a JSON object",
    },
    Rule {
        code: "2-200-0005",
        name: "PROJECT_JSON_REQUIRED_FIELD",
        severity: Severity::Error,
        message: "project.json is missing a required field",
    },
    Rule {
        code: "2-200-0006",
        name: "PROJECT_JSON_FIELD_TYPE",
        severity: Severity::Error,
        message: "project.json field has the wrong type",
    },
    Rule {
        code: "2-200-0007",
        name: "PROJECT_JSON_EMPTY_FIELD",
        severity: Severity::Error,
        message: "project.json field must not be empty",
    },
    Rule {
        code: "2-200-0008",
        name: "PROJECT_JSON_EMPTY_SOURCES",
        severity: Severity::Error,
        message: "project.json must include at least one source entry",
    },
    Rule {
        code: "2-200-0009",
        name: "PROJECT_JSON_UNKNOWN_KIND",
        severity: Severity::Warn,
        message: "project.json kind is not recognized",
    },
    // Reserved, not emitted. `mfb build` reports manifest problems and says
    // nothing on success, so there is no site that would raise this. Kept as a
    // reserved code rather than deleted so `2-200-0010` is never recycled for a
    // different meaning; the spec rows now say "reserved" instead of describing
    // a diagnostic users can never see (bug-326-A15).
    Rule {
        code: "2-200-0010",
        name: "PROJECT_JSON_VALID",
        severity: Severity::Info,
        message: "project.json passed validation",
    },
    Rule {
        code: "1-100-0001",
        name: "MFB_SOURCE_READ_FAILED",
        severity: Severity::Error,
        message: "MFBASIC source could not be read",
    },
    Rule {
        code: "1-100-0002",
        name: "MFB_SOURCE_ROOT_MISSING",
        severity: Severity::Error,
        message: "MFBASIC source root does not exist",
    },
    Rule {
        code: "1-100-0003",
        name: "MFB_SOURCE_EMPTY",
        severity: Severity::Error,
        message: "MFBASIC source root contains no source files",
    },
    Rule {
        code: "1-100-0004",
        name: "MFB_SOURCE_OUTSIDE_PROJECT",
        severity: Severity::Error,
        message: "MFBASIC source path resolves outside the project directory",
    },
    Rule {
        code: "1-100-0005",
        name: "MFB_SOURCE_OVERLAP",
        severity: Severity::Error,
        message: "MFBASIC source file is selected by more than one source entry",
    },
    Rule {
        code: "1-101-0001",
        name: "MFB_LEX_UNEXPECTED_CHARACTER",
        severity: Severity::Error,
        message: "lexer found an unexpected character",
    },
    Rule {
        code: "1-101-0002",
        name: "MFB_LEX_UNTERMINATED_STRING",
        severity: Severity::Error,
        message: "string literal is unterminated",
    },
    Rule {
        code: "1-101-0003",
        name: "MFB_LEX_INVALID_UNICODE_ESCAPE",
        severity: Severity::Error,
        message: "\\u{...} string escape is malformed",
    },
    Rule {
        code: "1-101-0004",
        name: "MFB_LEX_MALFORMED_NUMBER",
        severity: Severity::Error,
        message: "numeric literal is malformed",
    },
    Rule {
        code: "1-101-0005",
        name: "MFB_LEX_NUMBER_OUT_OF_RANGE",
        severity: Severity::Error,
        message: "numeric literal is out of range",
    },
    Rule {
        code: "1-102-0001",
        name: "MFB_PARSE_EXPECTED_EXPRESSION",
        severity: Severity::Error,
        message: "parser expected an expression",
    },
    // 1-102-0002 (MFB_PARSE_INVALID_FUNCTION_HEADER) dropped (bug-216): it had no
    // emit site — an invalid FUNC header is reported via MFB_PARSE_UNEXPECTED_TOKEN.
    Rule {
        code: "1-102-0003",
        name: "MFB_PARSE_INVALID_IDENTIFIER",
        severity: Severity::Error,
        message: "identifier is invalid",
    },
    Rule {
        code: "1-102-0004",
        name: "MFB_PARSE_UNEXPECTED_STATEMENT",
        severity: Severity::Error,
        message: "parser found an unexpected statement",
    },
    Rule {
        code: "1-102-0005",
        name: "MFB_PARSE_UNEXPECTED_TOKEN",
        severity: Severity::Error,
        message: "parser found an unexpected token",
    },
    Rule {
        code: "1-102-0006",
        name: "MFB_PARSE_UNTERMINATED_BLOCK",
        severity: Severity::Error,
        message: "parser reached end-of-file inside a block",
    },
    Rule {
        code: "1-102-0007",
        name: "MFB_PARSE_PIPELINE_PLACEHOLDER_MISSING",
        severity: Severity::Error,
        message: "pipeline expression is missing a placeholder",
    },
    Rule {
        code: "1-102-0008",
        name: "MFB_PARSE_MISSING_NATIVE_SYMBOL",
        severity: Severity::Error,
        message: "a native LINK function must declare its native SYMBOL",
    },
    Rule {
        code: "1-102-0009",
        name: "MFB_PARSE_MISSING_NATIVE_ABI",
        severity: Severity::Error,
        message: "a native LINK function must declare its ABI signature",
    },
    Rule {
        code: "1-102-0010",
        name: "MFB_PARSE_BLOCK_TOO_DEEP",
        severity: Severity::Error,
        message: "statement block nesting is too deep",
    },
    Rule {
        code: "2-201-0001",
        name: "IMPORT_PACKAGE_INVALID",
        severity: Severity::Error,
        message: "imported package binary could not be read",
    },
    Rule {
        code: "2-201-0002",
        name: "IMPORT_PACKAGE_NOT_DECLARED",
        severity: Severity::Error,
        message: "imported package is not declared",
    },
    Rule {
        code: "2-201-0003",
        name: "IMPORT_PACKAGE_NOT_INSTALLED",
        severity: Severity::Error,
        message: "declared package is not installed",
    },
    Rule {
        code: "2-201-0004",
        name: "IMPORT_LOCAL_PATH_INVALID",
        severity: Severity::Error,
        message: "local package source must be an absolute local URL",
    },
    Rule {
        code: "2-201-0005",
        name: "IMPORT_PACKAGE_MANIFEST_INVALID",
        severity: Severity::Error,
        message: "imported package manifest is invalid",
    },
    Rule {
        code: "2-201-0006",
        name: "IMPORT_PACKAGE_NAME_MISMATCH",
        severity: Severity::Error,
        message: "imported package manifest name does not match import",
    },
    Rule {
        code: "2-201-0007",
        name: "IMPORT_PACKAGE_KIND_INVALID",
        severity: Severity::Error,
        message: "imported source package must be a package",
    },
    Rule {
        code: "2-201-0008",
        name: "SYMBOL_DUPLICATE_IMPORT",
        severity: Severity::Error,
        message: "import is declared more than once",
    },
    Rule {
        code: "2-201-0009",
        name: "SYMBOL_DUPLICATE_LOCAL",
        severity: Severity::Error,
        message: "local symbol is declared more than once",
    },
    Rule {
        code: "2-201-0010",
        name: "SYMBOL_DUPLICATE_TOP_LEVEL",
        severity: Severity::Error,
        message: "top-level symbol is declared more than once",
    },
    Rule {
        code: "2-201-0011",
        name: "SYMBOL_UNKNOWN_IDENTIFIER",
        severity: Severity::Error,
        message: "identifier could not be resolved",
    },
    Rule {
        code: "2-201-0012",
        name: "SYMBOL_NOT_CALLABLE",
        severity: Severity::Error,
        message: "symbol cannot be called",
    },
    // 2-201-0013 (SYMBOL_NOT_VALUE) dropped (bug-216): it had no emit site — a
    // symbol used in value position is reported via SYMBOL_UNKNOWN_IDENTIFIER.
    Rule {
        code: "2-201-0014",
        name: "SYMBOL_UNKNOWN_IMPORT",
        severity: Severity::Error,
        message: "package-qualified symbol uses an unknown import",
    },
    Rule {
        code: "2-201-0015",
        name: "SYMBOL_UNKNOWN_TYPE",
        severity: Severity::Error,
        message: "type name could not be resolved",
    },
    Rule {
        code: "2-201-0016",
        name: "SYMBOL_RESERVED_BUILTIN_NAME",
        severity: Severity::Error,
        message: "function name is a reserved built-in and may not be redeclared",
    },
    Rule {
        code: "2-201-0017",
        name: "PRIVATE_SHADOWS_PUBLIC",
        severity: Severity::Warn,
        message: "PRIVATE declaration shadows a PUBLIC declaration of the same name within its file",
    },
    Rule {
        code: "2-201-0018",
        name: "PRIVATE_PATH_HASH_COLLISION",
        severity: Severity::Error,
        message: "internal: two source file paths produced the same file-scope hash",
    },
    Rule {
        code: "2-203-0001",
        name: "TYPE_BINARY_OPERATOR_MISMATCH",
        severity: Severity::Error,
        message: "binary operator operands have incompatible types",
    },
    Rule {
        code: "2-203-0002",
        name: "TYPE_UNARY_OPERATOR_MISMATCH",
        severity: Severity::Error,
        message: "unary operator operand has an incompatible type",
    },
    Rule {
        code: "2-203-0003",
        name: "TYPE_UNARY_OPERATOR_UNKNOWN",
        severity: Severity::Error,
        message: "unary operator is not recognized",
    },
    Rule {
        code: "2-203-0004",
        name: "TYPE_FOR_REQUIRES_NUMERIC",
        severity: Severity::Error,
        message: "FOR loop operands must be numeric",
    },
    Rule {
        code: "2-203-0005",
        name: "TYPE_FOR_STEP_ZERO",
        severity: Severity::Error,
        message: "FOR loop step must not be zero",
    },
    Rule {
        code: "2-203-0006",
        name: "TYPE_CONDITION_REQUIRES_BOOLEAN",
        severity: Severity::Error,
        message: "control-flow condition must be Boolean",
    },
    Rule {
        code: "2-203-0007",
        name: "TYPE_BINDING_MISMATCH",
        severity: Severity::Error,
        message: "binding initializer type does not match declared type",
    },
    Rule {
        code: "2-203-0008",
        name: "TYPE_ASSIGNMENT_MISMATCH",
        severity: Severity::Error,
        message: "assignment value type does not match binding type",
    },
    Rule {
        code: "2-203-0009",
        name: "TYPE_INTEGER_LITERAL_OVERFLOW",
        severity: Severity::Error,
        message: "integer literal is outside the Integer range",
    },
    Rule {
        code: "2-203-0010",
        name: "TYPE_FAIL_REQUIRES_ERROR",
        severity: Severity::Error,
        message: "FAIL requires an Error value",
    },
    Rule {
        code: "2-203-0011",
        name: "TYPE_PROPAGATE_REQUIRES_TRAP",
        severity: Severity::Error,
        message: "PROPAGATE requires a TRAP context",
    },
    Rule {
        code: "2-203-0012",
        name: "TYPE_TRAP_FALLTHROUGH",
        severity: Severity::Error,
        message: "TRAP path can fall through",
    },
    Rule {
        code: "2-203-0013",
        name: "TYPE_BYTE_LITERAL_OVERFLOW",
        severity: Severity::Error,
        message: "integer literal is outside the Byte range",
    },
    Rule {
        code: "2-203-0014",
        name: "TYPE_BYTE_LITERAL_UNDERFLOW",
        severity: Severity::Error,
        message: "integer literal is outside the Byte range",
    },
    Rule {
        code: "2-203-0015",
        name: "TYPE_FLOAT_LITERAL_OVERFLOW",
        severity: Severity::Error,
        message: "numeric literal is outside the Float range",
    },
    Rule {
        code: "2-203-0016",
        name: "TYPE_FLOAT_LITERAL_UNDERFLOW",
        severity: Severity::Error,
        message: "numeric literal is outside the Float range",
    },
    Rule {
        code: "2-203-0017",
        name: "TYPE_FIXED_LITERAL_OVERFLOW",
        severity: Severity::Error,
        message: "numeric literal is outside the Fixed range",
    },
    Rule {
        code: "2-203-0018",
        name: "TYPE_FIXED_LITERAL_UNDERFLOW",
        severity: Severity::Error,
        message: "numeric literal is outside the Fixed range",
    },
    Rule {
        code: "2-203-0019",
        name: "TYPE_LAMBDA_CAPTURE_UNSUPPORTED",
        severity: Severity::Error,
        message: "lambda capture is invalid",
    },
    Rule {
        code: "2-203-0020",
        name: "TYPE_BINDING_REQUIRES_TYPE_OR_VALUE",
        severity: Severity::Error,
        message: "binding requires a type annotation or initializer",
    },
    Rule {
        code: "2-203-0021",
        name: "TYPE_CALL_ARGUMENT_MISMATCH",
        severity: Severity::Error,
        message: "function call argument type does not match parameter type",
    },
    Rule {
        code: "2-203-0022",
        name: "TYPE_CALL_ARITY_MISMATCH",
        severity: Severity::Error,
        message: "function call has the wrong number of arguments",
    },
    Rule {
        code: "2-203-0023",
        name: "TYPE_CONSTRUCTOR_ARGUMENT_MISMATCH",
        severity: Severity::Error,
        message: "constructor argument type does not match field type",
    },
    Rule {
        code: "2-203-0024",
        name: "TYPE_CONSTRUCTOR_ARITY_MISMATCH",
        severity: Severity::Error,
        message: "constructor has the wrong number of arguments",
    },
    Rule {
        code: "2-203-0025",
        name: "TYPE_CONSTRUCTOR_REQUIRES_RECORD",
        severity: Severity::Error,
        message: "record constructor syntax requires a TYPE",
    },
    Rule {
        code: "2-203-0026",
        name: "TYPE_DEFAULT_ARG_ORDER",
        severity: Severity::Error,
        message: "default parameters must be trailing",
    },
    Rule {
        code: "2-203-0027",
        name: "TYPE_DEFAULT_VALUE_MISMATCH",
        severity: Severity::Error,
        message: "default parameter value has the wrong type",
    },
    Rule {
        code: "2-203-0028",
        name: "TYPE_DUPLICATE_ENUM_MEMBER",
        severity: Severity::Error,
        message: "enum member is declared more than once",
    },
    Rule {
        code: "2-203-0029",
        name: "TYPE_DUPLICATE_FIELD",
        severity: Severity::Error,
        message: "type field is declared more than once",
    },
    Rule {
        code: "2-203-0030",
        name: "TYPE_DUPLICATE_VARIANT",
        severity: Severity::Error,
        message: "union variant is declared more than once",
    },
    Rule {
        code: "2-203-0031",
        name: "TYPE_ENUM_REQUIRES_MEMBER",
        severity: Severity::Error,
        message: "enum must declare at least one member",
    },
    Rule {
        code: "2-203-0032",
        name: "TYPE_FUNC_MISSING_RETURN",
        severity: Severity::Error,
        message: "function is missing a return value",
    },
    Rule {
        code: "2-203-0033",
        name: "TYPE_FUNC_REQUIRES_RETURN_TYPE",
        severity: Severity::Error,
        message: "FUNC must declare a return type",
    },
    Rule {
        code: "2-203-0034",
        name: "TYPE_FIELD_ACCESS_REQUIRES_RECORD",
        severity: Severity::Error,
        message: "field access requires a record value",
    },
    Rule {
        code: "2-203-0035",
        name: "TYPE_LET_REQUIRES_VALUE",
        severity: Severity::Error,
        message: "immutable binding must have an initializer",
    },
    Rule {
        code: "2-203-0036",
        name: "TYPE_MEMBER_NOT_VISIBLE",
        severity: Severity::Error,
        message: "type member is not visible from this scope",
    },
    Rule {
        code: "2-203-0037",
        name: "TYPE_PARAM_REQUIRES_TYPE",
        severity: Severity::Error,
        message: "parameter must declare a type",
    },
    Rule {
        code: "2-203-0038",
        name: "TYPE_READ_ONLY_RECORD_UPDATE",
        severity: Severity::Error,
        message: "read-only record cannot be updated",
    },
    Rule {
        code: "2-203-0039",
        name: "TYPE_READ_ONLY_RECORD_CONSTRUCTOR",
        severity: Severity::Error,
        message: "read-only record cannot be constructed",
    },
    Rule {
        code: "2-203-0040",
        name: "TYPE_RESULT_IS_IMPLICIT",
        severity: Severity::Error,
        message: "Result return wrapping is implicit",
    },
    Rule {
        code: "2-203-0041",
        name: "TYPE_RETURN_MISMATCH",
        severity: Severity::Error,
        message: "return value type does not match function success type",
    },
    Rule {
        code: "2-203-0042",
        name: "TYPE_SUB_CANNOT_RETURN_VALUE",
        severity: Severity::Error,
        message: "SUB cannot return a value",
    },
    Rule {
        code: "2-203-0043",
        name: "TYPE_UNKNOWN_VALUE",
        severity: Severity::Error,
        message: "value type could not be determined",
    },
    Rule {
        code: "2-203-0044",
        name: "TYPE_UNKNOWN_ENUM_MEMBER",
        severity: Severity::Error,
        message: "enum member does not exist",
    },
    Rule {
        code: "2-203-0045",
        name: "TYPE_UNKNOWN_FIELD",
        severity: Severity::Error,
        message: "record field does not exist",
    },
    Rule {
        code: "2-203-0046",
        name: "TYPE_UNION_INCLUDE_REQUIRES_UNION",
        severity: Severity::Error,
        message: "union includes must name union types",
    },
    // 2-203-0047 (TYPE_VARIANT_CONSTRUCTOR_AMBIGUOUS) dropped (bug-216): it had no
    // emit site — variant constructors resolve unambiguously by their unique name.
    Rule {
        code: "2-203-0048",
        name: "TYPE_ASSIGN_REQUIRES_MUT",
        severity: Severity::Error,
        message: "assignment target must be mutable",
    },
    Rule {
        code: "2-203-0049",
        name: "TYPE_MATCH_PATTERN_MISMATCH",
        severity: Severity::Error,
        message: "match pattern type does not match the scrutinee type",
    },
    Rule {
        code: "2-203-0050",
        name: "TYPE_FOR_EACH_REQUIRES_COLLECTION",
        severity: Severity::Error,
        message: "FOR EACH source must be a List or Map",
    },
    Rule {
        code: "2-203-0051",
        name: "TYPE_LIST_ELEMENT_MISMATCH",
        severity: Severity::Error,
        message: "list element type does not match the expected element type",
    },
    Rule {
        code: "2-203-0052",
        name: "TYPE_MAP_KEY_MISMATCH",
        severity: Severity::Error,
        message: "map key type does not match the declared key type",
    },
    Rule {
        code: "2-203-0053",
        name: "TYPE_MAP_VALUE_MISMATCH",
        severity: Severity::Error,
        message: "map value type does not match the declared value type",
    },
    Rule {
        code: "2-203-0055",
        name: "TYPE_USE_AFTER_MOVE",
        severity: Severity::Error,
        message: "binding is used after move",
    },
    Rule {
        code: "2-203-0056",
        name: "TYPE_COLLECTION_OWNERSHIP_VIOLATION",
        severity: Severity::Error,
        message: "ordinary collections cannot store resource or thread ownership",
    },
    // RETIRED by plan-59-E, not emitted. A resource is owned by the outermost
    // scope that touches it, so a collection element of resource type is a
    // pointer to the one resource like any other holder, and binding or returning
    // one is legal. Kept as a reserved row rather than deleted so `2-203-0100` is
    // never recycled for a different meaning — the `PROJECT_JSON_VALID`
    // (`2-200-0010`) precedent above.
    Rule {
        code: "2-203-0100",
        name: "TYPE_RESOURCE_ELEMENT_NOT_OWNER",
        severity: Severity::Error,
        message: "reserved: retired by plan-59-E (resource-scoped ownership)",
    },
    Rule {
        code: "2-203-0101",
        name: "TYPE_OVERLOAD_AMBIGUOUS",
        severity: Severity::Error,
        message: "return-type overload cannot be resolved without an expected type",
    },
    Rule {
        code: "2-203-0102",
        name: "TYPE_INSTANTIATION_TOO_DEEP",
        severity: Severity::Error,
        message: "template instantiation is too deep",
    },
    Rule {
        code: "2-203-0058",
        name: "TYPE_DUPLICATE_ARGUMENT_NAME",
        severity: Severity::Error,
        message: "call argument is supplied more than once",
    },
    Rule {
        code: "2-203-0059",
        name: "TYPE_UNKNOWN_ARGUMENT_NAME",
        severity: Severity::Error,
        message: "call argument name does not match any parameter",
    },
    Rule {
        code: "2-203-0060",
        name: "TYPE_MUT_REQUIRES_DEFAULTABLE_TYPE",
        severity: Severity::Error,
        message: "uninitialized mutable binding requires a defaultable type",
    },
    Rule {
        code: "2-203-0061",
        name: "TYPE_REQUIRES_COMPARABLE",
        severity: Severity::Error,
        message: "operation requires a comparable type",
    },
    Rule {
        code: "2-203-0062",
        name: "TYPE_MATCH_NOT_EXHAUSTIVE",
        severity: Severity::Error,
        message: "match cases do not cover every possible value",
    },
    Rule {
        code: "2-203-0063",
        name: "TYPE_THREAD_NOT_SENDABLE",
        severity: Severity::Error,
        message: "thread boundary type is not sendable",
    },
    Rule {
        code: "2-203-0064",
        name: "TYPE_UNION_MEMBER_REQUIRES_TYPE",
        severity: Severity::Error,
        message: "union members must name concrete TYPE declarations",
    },
    Rule {
        code: "2-203-0065",
        name: "TYPE_RECURSIVE_RECORD_REQUIRES_INDIRECTION",
        severity: Severity::Error,
        message: "recursive record cycle must pass through a List, Map, or UNION",
    },
    Rule {
        code: "2-203-0066",
        name: "TYPE_INLINE_TRAP_FALLS_THROUGH",
        severity: Severity::Error,
        message: "inline TRAP handler path neither recovers nor diverges",
    },
    Rule {
        code: "2-203-0067",
        name: "TYPE_RECOVER_TYPE_MISMATCH",
        severity: Severity::Error,
        message: "RECOVER value does not match the trapped expression's success type",
    },
    Rule {
        code: "2-203-0068",
        name: "TYPE_RECOVER_OUTSIDE_INLINE_TRAP",
        severity: Severity::Error,
        message: "RECOVER is valid only inside an inline TRAP handler",
    },
    Rule {
        code: "2-203-0069",
        name: "TYPE_INLINE_TRAP_REQUIRES_FALLIBLE",
        severity: Severity::Error,
        message: "inline TRAP requires a fallible call",
    },
    // 2-203-0102 (TYPE_INLINE_TRAP_ON_INLINED_BUILTIN) retired in plan-26-C: every
    // inline-lowered builtin is now trappable (raw-supported or infallible), so an
    // inline TRAP is legal on all of them. The code is not reused.
    Rule {
        code: "2-203-0104",
        name: "TYPE_INLINE_TRAP_DEAD_HANDLER",
        severity: Severity::Warn,
        message: "inline TRAP handler is unreachable — the guarded call cannot fail",
    },
    Rule {
        code: "2-203-0103",
        name: "EXPORT_IN_EXECUTABLE",
        severity: Severity::Error,
        message: "EXPORT is only valid in a package project; use PUBLIC (the default) in an executable",
    },
    Rule {
        code: "2-203-0105",
        name: "TYPE_MONEY_LITERAL_OVERFLOW",
        severity: Severity::Error,
        message: "numeric literal is outside the Money range",
    },
    Rule {
        code: "2-203-0106",
        name: "TYPE_MONEY_LITERAL_UNDERFLOW",
        severity: Severity::Error,
        message: "numeric literal is outside the Money range",
    },
    Rule {
        code: "2-203-0107",
        name: "TYPE_MONEY_OPERATION_INVALID",
        severity: Severity::Error,
        message: "operation is not valid for Money operands",
    },
    Rule {
        code: "2-203-0108",
        name: "TYPE_MONEY_LITERAL_PRECISION",
        severity: Severity::Warn,
        message: "Money literal has more than 5 fractional digits and is rounded",
    },
    Rule {
        code: "2-203-0109",
        name: "MONEY_INEXACT_FLOAT_LITERAL",
        severity: Severity::Warn,
        message: "scaling Money by a bare decimal literal uses inexact Float arithmetic",
    },
    Rule {
        code: "2-203-0110",
        name: "TYPE_SCALAR_LITERAL_EMPTY",
        severity: Severity::Error,
        message: "a backtick scalar literal must contain exactly one Unicode scalar",
    },
    Rule {
        code: "2-203-0111",
        name: "TYPE_SCALAR_LITERAL_TOO_MANY",
        severity: Severity::Error,
        message: "a backtick scalar literal must contain exactly one Unicode scalar",
    },
    Rule {
        code: "2-203-0112",
        name: "TYPE_SCALAR_LITERAL_INVALID",
        severity: Severity::Error,
        message: "a scalar literal must name a valid Unicode scalar value",
    },
    Rule {
        code: "2-203-0113",
        name: "TYPE_ISOLATED_NOT_VISIBLE",
        severity: Severity::Error,
        message: "ISOLATED function must be a project-visible FUNC declaration",
    },
    Rule {
        code: "2-203-0114",
        name: "NATIVE_LIBRARY_MISSING",
        severity: Severity::Error,
        message: "a LINK block names a library with no matching project.json `libraries` entry",
    },
    Rule {
        code: "2-203-0115",
        name: "NATIVE_LIBRARY_TARGET_UNCOVERED",
        severity: Severity::Warn,
        message: "a supported build target has no `libraries` locator for a linked native library",
    },
    Rule {
        code: "2-203-0116",
        name: "NATIVE_LIBRARY_SOURCE_UNREADABLE",
        severity: Severity::Error,
        message: "a `vendor` locator's file under the project's `vendor/` directory is missing or cannot be read to hash it",
    },
    Rule {
        code: "2-203-0117",
        name: "NATIVE_LIBRARY_UNUSED",
        severity: Severity::Warn,
        message: "a project.json `libraries` entry has no matching LINK block in code",
    },
    Rule {
        code: "2-203-0118",
        name: "NATIVE_LIBRARY_NO_MATCH",
        severity: Severity::Error,
        message: "no native library locator matches the target being built",
    },
    Rule {
        code: "2-203-0119",
        name: "NATIVE_LIBRARY_AMBIGUOUS",
        severity: Severity::Error,
        message: "two equally-specific native library locators match the target being built",
    },
    Rule {
        code: "2-203-0120",
        name: "NATIVE_LIBRARY_FILE_MISSING",
        severity: Severity::Error,
        message: "a resolved `vendor` native library is missing from the consumer project's `vendor/` directory",
    },
    Rule {
        code: "2-203-0121",
        name: "NATIVE_LIBRARY_HASH_MISMATCH",
        severity: Severity::Error,
        message: "a resolved `vendor` native library does not match the sha256 the binding recorded for it",
    },
    Rule {
        code: "2-203-0122",
        name: "NATIVE_LIBRARY_VENDOR_COLLISION",
        severity: Severity::Error,
        message: "two declaring units vendor different native libraries that copy to the same output filename",
    },
    Rule {
        code: "2-203-0123",
        name: "NATIVE_ABI_UNKNOWN_CTYPE",
        severity: Severity::Error,
        message: "an ABI slot or return names a C type the marshaling backend does not implement",
    },
    Rule {
        code: "2-203-0124",
        name: "NATIVE_CSTRUCT_INVALID",
        severity: Severity::Error,
        message: "a CSTRUCT declaration is not a layout the compiler can compute faithfully",
    },
    Rule {
        code: "2-203-0125",
        name: "NATIVE_CSTRUCT_TOO_LARGE",
        severity: Severity::Error,
        message: "a CSTRUCT lays out larger than the maximum native struct size",
    },
    Rule {
        code: "2-203-0127",
        name: "NATIVE_STRUCT_FIELD_MISMATCH",
        severity: Severity::Error,
        message: "a CSTRUCT and the record it maps to differ by field name, type, or coverage",
    },
    Rule {
        code: "2-203-0128",
        name: "NATIVE_BIND_IN_INVALID",
        severity: Severity::Error,
        message: "a BIND IN block names an unknown slot or field, or binds a value it cannot marshal",
    },
    Rule {
        code: "2-203-0126",
        name: "NATIVE_CSTRUCT_ESCAPE",
        severity: Severity::Error,
        message: "a CSTRUCT name is used outside its LINK block, where only its mapped record type is nameable",
    },
    Rule {
        code: "2-203-0070",
        name: "TYPE_RESULT_NOT_USER_VISIBLE",
        severity: Severity::Error,
        message: "Result is an internal type and cannot be named in user code",
    },
    Rule {
        code: "2-203-0071",
        name: "TYPE_RESULT_NOT_MATCHABLE",
        severity: Severity::Error,
        message: "Ok and Error are not matchable as Result members in user code",
    },
    Rule {
        code: "2-203-0072",
        name: "TYPE_THREAD_RESULT_REMOVED",
        severity: Severity::Error,
        message: "the thread result field is removed; use thread::waitFor",
    },
    Rule {
        code: "2-203-0073",
        name: "SUB_RETURN_FORBIDDEN",
        severity: Severity::Error,
        message: "RETURN is forbidden in a SUB; use EXIT SUB",
    },
    Rule {
        code: "2-203-0074",
        name: "TYPE_SUB_HAS_NO_VALUE",
        severity: Severity::Error,
        message: "a SUB call produces no value and cannot be used in value position",
    },
    Rule {
        code: "2-203-0075",
        name: "EXIT_NO_MATCHING_LOOP",
        severity: Severity::Error,
        message: "EXIT has no matching enclosing loop",
    },
    Rule {
        code: "2-203-0076",
        name: "CONTINUE_NO_MATCHING_LOOP",
        severity: Severity::Error,
        message: "CONTINUE has no matching enclosing loop",
    },
    Rule {
        code: "2-203-0077",
        name: "EXIT_SUB_IN_FUNC",
        severity: Severity::Error,
        message: "EXIT SUB is valid only inside a SUB",
    },
    Rule {
        code: "2-203-0078",
        name: "EXIT_FUNC_FORBIDDEN",
        severity: Severity::Error,
        message: "EXIT FUNC is forbidden; functions must RETURN a value",
    },
    Rule {
        code: "2-203-0079",
        name: "TYPE_EXIT_PROGRAM_REQUIRES_INTEGER",
        severity: Severity::Error,
        message: "EXIT PROGRAM requires an Integer exit code",
    },
    Rule {
        code: "2-203-0080",
        name: "EXIT_PROGRAM_CODE_OUT_OF_RANGE",
        severity: Severity::Error,
        message: "EXIT PROGRAM constant exit code is outside the host range",
    },
    Rule {
        code: "2-203-0081",
        name: "UNREACHABLE_AFTER_EXIT",
        severity: Severity::Error,
        message: "statement is unreachable after EXIT or CONTINUE",
    },
    Rule {
        code: "2-203-0082",
        name: "TYPE_RESOURCE_REQUIRES_RES",
        severity: Severity::Error,
        message: "resource must be bound with RES",
    },
    Rule {
        code: "2-203-0083",
        name: "TYPE_RES_REQUIRES_RESOURCE",
        severity: Severity::Error,
        message: "RES binds only resource types",
    },
    Rule {
        code: "2-203-0084",
        name: "TYPE_RESOURCE_FIELD_FORBIDDEN",
        severity: Severity::Error,
        message: "a record field cannot be a resource",
    },
    Rule {
        code: "2-203-0085",
        name: "TYPE_STATE_INVALID",
        severity: Severity::Error,
        message: "STATE must be a copyable, defaultable data type",
    },
    // RETIRED by plan-59-E, not emitted. Ownership moved from the binding to the
    // outermost scope that touches the resource: any holder of the pointer may
    // close, `RETURN`, or transfer it, and the owning scope closes it once if
    // nobody already did. What replaces this rule is a runtime backstop, not
    // nothing — plan-59-B's closed/moved guard makes a second close a defined
    // `ErrResourceClosed`, and `TYPE_USE_AFTER_MOVE` still catches every case it
    // can prove (now including aliased ones, plan-59-E Phase 2).
    //
    // Reserved rather than deleted so `2-203-0086` is never recycled for a
    // different meaning — the `PROJECT_JSON_VALID` (`2-200-0010`) precedent.
    Rule {
        code: "2-203-0086",
        name: "TYPE_RESOURCE_INVALIDATE_NOT_OWNER",
        severity: Severity::Error,
        message: "reserved: retired by plan-59-E (resource-scoped ownership)",
    },
    Rule {
        code: "2-203-0087",
        name: "TYPE_MIXED_RESOURCE_UNION",
        severity: Severity::Error,
        message: "a union must be all-data or all-resource, never mixed",
    },
    Rule {
        code: "2-203-0088",
        name: "TYPE_UNION_STATE_FORBIDDEN",
        severity: Severity::Error,
        message: "a resource union carries no STATE",
    },
    Rule {
        code: "2-203-0129",
        name: "TYPE_STATE_MISMATCH",
        severity: Severity::Error,
        message: "a resource's STATE type is fixed at its owning binding and every other declaration of it must agree",
    },
    Rule {
        code: "2-203-0133",
        name: "TYPE_STATE_OPAQUE_NARROWING",
        severity: Severity::Error,
        message: "an opaque resource STATE cannot be narrowed to a concrete STATE type",
    },
    Rule {
        code: "2-203-0131",
        name: "TYPE_RESOURCE_RETURN_ORDER",
        severity: Severity::Error,
        message: "a collection that carries a returned resource must be declared before that resource",
    },
    Rule {
        code: "2-203-0130",
        name: "NATIVE_BIND_STATE_INVALID",
        severity: Severity::Error,
        message: "a BIND STATE must name the native function's stateful resource return and an OUT CSTRUCT slot whose record is the resource's STATE type",
    },
    Rule {
        code: "2-203-0089",
        name: "RESOURCE_CLOSE_NOT_NATIVE",
        severity: Severity::Error,
        message: "a resource's CLOSE BY op must be a native LINK function",
    },
    Rule {
        code: "2-203-0090",
        name: "RESOURCE_CLOSE_MISSING",
        severity: Severity::Error,
        message: "a resource's CLOSE BY op names no function in its LINK block",
    },
    Rule {
        code: "2-203-0091",
        name: "RESOURCE_CLOSE_SIGNATURE",
        severity: Severity::Error,
        message: "a close op must consume exactly one RES parameter of its resource",
    },
    Rule {
        code: "2-203-0092",
        name: "NATIVE_CPTR_ESCAPE",
        severity: Severity::Error,
        message: "a raw C ABI type may appear only inside an ABI slot",
    },
    Rule {
        code: "2-203-0093",
        name: "NATIVE_ABI_RESULT_MARKER",
        severity: Severity::Error,
        message: "a native function's ABI result marker is malformed",
    },
    Rule {
        code: "2-203-0094",
        name: "NATIVE_ABI_UNBOUND_SLOT",
        severity: Severity::Error,
        message: "an ABI slot binds to no parameter, CONST pin, or result marker",
    },
    Rule {
        code: "2-203-0095",
        name: "NATIVE_ABI_UNBOUND_PARAM",
        severity: Severity::Error,
        message: "a native function parameter has no matching ABI slot",
    },
    Rule {
        code: "2-203-0096",
        name: "NATIVE_ABI_NO_RESULT",
        severity: Severity::Error,
        message: "a value-returning native function marks no ABI result",
    },
    Rule {
        code: "2-203-0097",
        name: "NATIVE_CONST_OUT",
        severity: Severity::Error,
        message: "a CONST-pinned ABI slot cannot also be OUT",
    },
    Rule {
        code: "2-203-0098",
        name: "NATIVE_CONST_UNKNOWN_SLOT",
        severity: Severity::Error,
        message: "a CONST pin names an unknown ABI slot",
    },
    Rule {
        code: "2-203-0099",
        name: "NATIVE_FREE_INVALID",
        severity: Severity::Error,
        message: "a FREE block is malformed: it must release the `return` CPtr produced slot through a deallocator taking one CPtr parameter and returning CVoid",
    },
    Rule {
        code: "2-203-0132",
        name: "NATIVE_BUFFER_INVALID",
        severity: Severity::Error,
        message: "a CBuffer slot or BUFFER SIZE clause is invalid: a CBuffer must be an OUT slot with exactly one BUFFER clause, named by RETURN, on a wrapper returning List OF Byte",
    },
    Rule {
        code: "2-203-0134",
        name: "RESOURCE_SHADOWS_BUILTIN",
        severity: Severity::Error,
        message: "a RESOURCE declaration cannot reuse the name of a built-in resource type",
    },
    Rule {
        code: "2-200-0011",
        name: "PROJECT_ENTRY_INVALID",
        severity: Severity::Error,
        message: "project entry point is invalid",
    },
    Rule {
        code: "2-200-0012",
        name: "PROJECT_JSON_UNKNOWN_MODE",
        severity: Severity::Warn,
        message: "project.json mode is not recognized",
    },
    Rule {
        code: "2-200-0013",
        name: "PROJECT_JSON_ICON_MISSING",
        severity: Severity::Error,
        message: "project.json icon path does not resolve to a readable file",
    },
    Rule {
        code: "2-200-0014",
        name: "PROJECT_JSON_LIBRARY_INVALID",
        severity: Severity::Error,
        message: "a project.json `libraries` locator is malformed, carries an unknown os/arch/libc/type token, or names a `source` that is not a bare filename",
    },
    Rule {
        code: "2-200-0015",
        name: "PROJECT_JSON_LIBRARY_SOURCE_CONFLICT",
        severity: Severity::Error,
        message: "two project.json `libraries` vendor locators declare the same `source` filename",
    },
    Rule {
        code: "2-200-0016",
        name: "PROJECT_JSON_DESCRIPTION_MISSING",
        severity: Severity::Warn,
        message: "a project.json with `kind: \"package\"` should declare a `description`",
    },
    Rule {
        code: "2-200-0100",
        name: "BUILD_FAILED",
        severity: Severity::Error,
        message: "build failed for an unclassified orchestration reason",
    },
    Rule {
        code: "2-200-0101",
        name: "FMT_CHECK_FAILED",
        severity: Severity::Error,
        message: "one or more source files are not formatted (mfb fmt --check)",
    },
    Rule {
        code: "2-205-0001",
        name: "PACKAGE_VERSION_UNSUPPORTED",
        severity: Severity::Error,
        message: "package binary representation or metadata version is unsupported",
    },
    Rule {
        code: "2-205-0002",
        name: "NATIVE_MANIFEST_INVALID",
        severity: Severity::Error,
        message: "native-link metadata in a package is malformed or inconsistent",
    },
    Rule {
        code: "3-302-0001",
        name: "VERIFICATION_FAILED",
        severity: Severity::Error,
        message: "binary representation or native validation failed",
    },
    Rule {
        code: "3-304-0001",
        name: "TARGET_UNSUPPORTED",
        severity: Severity::Error,
        message: "requested target OS, CPU, or ABI is unsupported",
    },
    Rule {
        code: "5-500-0001",
        name: "LINK_FAILED",
        severity: Severity::Error,
        message: "linking packages, native libraries, symbols, objects, or executables failed",
    },
    Rule {
        code: "6-603-0001",
        name: "LOCKFILE_MISMATCH",
        severity: Severity::Error,
        message: "resolved package state does not match mfb.lock",
    },
    Rule {
        code: "6-605-0001",
        name: "PACKAGE_INVALID",
        severity: Severity::Error,
        message: "package container is malformed or incompatible",
    },
    Rule {
        code: "6-605-0002",
        name: "PACKAGE_SIGNATURE_INVALID",
        severity: Severity::Error,
        message: "package signature, hash, or trust record is missing or invalid",
    },
    // --- plan-23 §3.5 client verification chain refusals ---
    Rule {
        code: "6-605-0003",
        name: "PACKAGE_IDENT_KEY_UNTRUSTED",
        severity: Severity::Error,
        message: "package identKey does not match the pinned trust anchor",
    },
    Rule {
        code: "6-605-0004",
        name: "PACKAGE_ATTESTATION_INVALID",
        severity: Severity::Error,
        message: "package attestation is missing, unverifiable, or pins a different package",
    },
    Rule {
        code: "6-605-0005",
        name: "PACKAGE_PROOF_INVALID",
        severity: Severity::Error,
        message: "package proof is missing, unverifiable, or pins a different package",
    },
    Rule {
        code: "6-605-0006",
        name: "PACKAGE_PAYLOAD_HASH_MISMATCH",
        severity: Severity::Error,
        message: "package payload does not match the signed packageBinaryHash",
    },
    Rule {
        code: "6-605-0007",
        name: "PACKAGE_UNSIGNED_REMOTE",
        severity: Severity::Error,
        message: "unsigned package from a non-local source requires --unsigned",
    },
    Rule {
        code: "6-605-0008",
        name: "PACKAGE_IDENT_REANCHORED",
        severity: Severity::Error,
        message: "owner ident changed with no chain link from the pinned key; verify out-of-band",
    },
    Rule {
        code: "6-605-0009",
        name: "REGISTRY_LOG_ROLLBACK",
        severity: Severity::Error,
        message: "registry transparency log shrank or forked relative to the pinned checkpoint",
    },
    Rule {
        code: "6-605-0010",
        name: "PACKAGE_VENDOR_BLOB_MISSING",
        severity: Severity::Error,
        message: "registry has no blob for a vendored native library the package's section-10 table names",
    },
    Rule {
        code: "6-605-0011",
        name: "PACKAGE_VENDOR_BLOB_HASH_MISMATCH",
        severity: Severity::Error,
        message: "downloaded vendor blob does not match the sha256 recorded in the signed section-10 table",
    },
    Rule {
        code: "3-304-0002",
        name: "PACKAGE_NATIVE_OUTPUT_UNSUPPORTED",
        severity: Severity::Error,
        message: "package projects do not support the requested native output mode",
    },
    // --- DOC block structure (lexer/parser), plan-09-doc.md ---
    Rule {
        code: "1-103-0001",
        name: "DOC_UNTERMINATED",
        severity: Severity::Error,
        message: "DOC block was not closed with END DOC",
    },
    Rule {
        code: "1-103-0002",
        name: "DOC_BAD_HEADER",
        severity: Severity::Error,
        message: "DOC block header must be FUNC, SUB, TYPE, UNION, ENUM, or PACKAGE",
    },
    Rule {
        code: "1-103-0003",
        name: "DOC_UNKNOWN_LINE",
        severity: Severity::Error,
        message: "DOC line keyword is not recognized",
    },
    Rule {
        code: "1-103-0004",
        name: "DOC_EXAMPLE_UNTERMINATED",
        severity: Severity::Error,
        message: "EXAMPLE block was not closed with END EXAMPLE",
    },
    // --- DOC block semantics (resolver), plan-09-doc.md §4 ---
    Rule {
        code: "2-205-0001",
        name: "DOC_UNRESOLVED",
        severity: Severity::Error,
        message: "DOC header name does not resolve to any declaration in the package",
    },
    Rule {
        code: "2-205-0002",
        name: "DOC_NAME_MISMATCH",
        severity: Severity::Error,
        message: "DOC header keyword does not match the kind of the named declaration",
    },
    Rule {
        code: "2-205-0003",
        name: "DOC_DUPLICATE",
        severity: Severity::Error,
        message: "two DOC blocks name the same declaration",
    },
    Rule {
        code: "2-205-0004",
        name: "DOC_ARG_UNKNOWN",
        severity: Severity::Error,
        message: "ARG name does not match any parameter in the target signature",
    },
    Rule {
        code: "2-205-0005",
        name: "DOC_ARG_DUPLICATE",
        severity: Severity::Error,
        message: "two ARG lines document the same parameter",
    },
    Rule {
        code: "2-205-0006",
        name: "DOC_ARG_INVALID_CONTEXT",
        severity: Severity::Error,
        message: "ARG is not valid in a TYPE, UNION, ENUM, or PACKAGE doc block",
    },
    Rule {
        code: "2-205-0007",
        name: "DOC_PROP_UNKNOWN",
        severity: Severity::Error,
        message: "PROP name does not match any member of the target type",
    },
    Rule {
        code: "2-205-0008",
        name: "DOC_PROP_DUPLICATE",
        severity: Severity::Error,
        message: "two PROP lines document the same member",
    },
    Rule {
        code: "2-205-0009",
        name: "DOC_PROP_INVALID_CONTEXT",
        severity: Severity::Error,
        message: "PROP is valid only in TYPE, UNION, and ENUM doc blocks",
    },
    Rule {
        code: "2-205-0010",
        name: "DOC_RET_INVALID_CONTEXT",
        severity: Severity::Error,
        message: "RET is not valid in a TYPE, UNION, ENUM, or PACKAGE doc block",
    },
    Rule {
        code: "2-205-0011",
        name: "DOC_DUPLICATE_RET",
        severity: Severity::Error,
        message: "more than one RET line in a doc block",
    },
    Rule {
        code: "2-205-0012",
        name: "DOC_ERROR_INVALID_CONTEXT",
        severity: Severity::Error,
        message: "ERROR is not valid in a TYPE, UNION, ENUM, or PACKAGE doc block",
    },
    Rule {
        code: "2-205-0013",
        name: "DOC_DUPLICATE_EXAMPLE",
        severity: Severity::Error,
        message: "more than one EXAMPLE block in a doc block",
    },
    Rule {
        code: "2-205-0014",
        name: "DOC_DUPLICATE_PACKAGE",
        severity: Severity::Error,
        message: "more than one PACKAGE doc block in the package",
    },
    Rule {
        code: "2-205-0015",
        name: "DOC_DUPLICATE_ATTR",
        severity: Severity::Error,
        message: "the INTERNAL attribute appears more than once on one DOC line",
    },
    Rule {
        code: "2-205-0016",
        name: "DOC_UNKNOWN_ATTR",
        severity: Severity::Error,
        message: "unrecognized keyword in the DOC-line attribute position",
    },
    Rule {
        code: "2-205-0017",
        name: "DOC_INTERNAL_INVALID_CONTEXT",
        severity: Severity::Error,
        message: "INTERNAL is not valid on a PACKAGE doc block",
    },
    Rule {
        code: "2-205-0018",
        name: "DOC_DUPLICATE_DEPRECATED",
        severity: Severity::Error,
        message: "more than one DEPRECATED line in a doc block",
    },
    Rule {
        code: "2-205-0019",
        name: "DOC_GROUP_INVALID_CONTEXT",
        severity: Severity::Error,
        message: "GROUP is valid only on FUNC and SUB doc blocks",
    },
    Rule {
        code: "2-205-0020",
        name: "DOC_DUPLICATE_GROUP",
        severity: Severity::Error,
        message: "more than one GROUP line in a doc block",
    },
    Rule {
        code: "2-205-0021",
        name: "DOC_OVERLOAD_UNRESOLVED",
        severity: Severity::Error,
        message: "DOC header parameter types match no overload of the declaration",
    },
    // Test framework (plan-18-testing.md) — TESTING/TGROUP/TCASE parse errors and
    // the assertion-builtin semantic checks.
    Rule {
        code: "1-102-0010",
        name: "MFB_PARSE_TESTING_EXPECTED_TGROUP",
        severity: Severity::Error,
        message: "a TESTING block may contain only TGROUP groups",
    },
    Rule {
        code: "1-102-0011",
        name: "MFB_PARSE_TESTING_EXPECTED_TCASE",
        severity: Severity::Error,
        message: "a TGROUP may contain only TCASE cases and nested TGROUP groups",
    },
    Rule {
        code: "1-102-0012",
        name: "MFB_PARSE_TESTING_DESCRIPTION",
        severity: Severity::Error,
        message: "a TGROUP/TCASE requires a string-literal description",
    },
    Rule {
        code: "2-208-0001",
        name: "TESTING_EXPECT_OUTSIDE_TCASE",
        severity: Severity::Error,
        message: "assertion builtins are valid only inside a TCASE body",
    },
    Rule {
        code: "2-208-0002",
        name: "TESTING_EXPECT_ARITY",
        severity: Severity::Error,
        message: "assertion builtin called with the wrong number of arguments",
    },
    Rule {
        code: "2-208-0003",
        name: "TESTING_EXPECT_INCOMPARABLE",
        severity: Severity::Error,
        message: "expectEqual/expectNEqual operands must be comparable with `=`",
    },
    Rule {
        code: "2-208-0004",
        name: "TESTING_EXPECT_NOT_PRINTABLE",
        severity: Severity::Error,
        message: "expectEqual/expectNEqual operands must be printable for the failure message",
    },
    Rule {
        code: "2-208-0005",
        name: "TESTING_EXPECT_CODE_TYPE",
        severity: Severity::Error,
        message: "expectTrap expected-code argument must be an Integer",
    },
    Rule {
        code: "2-208-0006",
        name: "TESTING_EXPECT_TRAP_REQUIRES_FALLIBLE",
        severity: Severity::Error,
        message: "expectTrap/expectNTrap require a call (not a package constant) to trap-guard",
    },
    // 2-208-0007 (TESTING_EXPECT_TRAP_INLINE_BUILTIN) retired in plan-26-C: the
    // assertions now accept every call inline TRAP accepts, so no inline-compiled
    // builtin is rejected. The code is not reused.
    Rule {
        code: "2-208-0008",
        name: "TESTING_EXPECT_TYPE_MISMATCH",
        severity: Severity::Error,
        message: "typed assertion operands must both be the named type",
    },
];
