"""Shared helpers for crafting malicious `.mfp` packages (audit-1 fixtures).

The security fixtures under `tests/syntax/security/pkg-0*` each import a deliberately
malformed or tampered compiled package to prove the compiler's decode/verify
path rejects it. The malicious `.mfp` files are *generated* (never hand-typed)
by the `generate.py` script that lives next to each source package, using the
primitives in this module. The generated bytes are committed; the scripts exist
for reproducibility and to document exactly how each attack is constructed.

The layout of a `.mfp` container (outer framing) and its inner `MFPC` payload is
described in `src/docs/spec/package/01_container-format.md` and mirrored by the
Rust reader in `src/binary_repr/reader.rs` / `repository/src/package.rs`.

No third-party import is required for the structural mutators. Signing (PKG-01)
uses the standard-library-adjacent `cryptography` package when available; the
committed fixtures were produced with it.
"""

from __future__ import annotations

import hashlib
import os
import re
import struct

# `BINARY_REPR_VERSION`, READ FROM src/ir/binary.rs rather than restated here.
#
# The hand-encoded MFBR bodies below reproduce that format byte for byte, so this
# must move with it — a stale value makes every crafted fixture fail on the
# VERSION GATE instead of on the corruption it is meant to prove, silently
# converting a suite of decode-hardening tests into a suite of version tests.
#
# That is not hypothetical: it happened at the 5->6 bump (plan-58-C), where four
# of the eight fixtures started failing on the version instead of their own
# property. The constant was previously hand-maintained with a comment warning
# about exactly this. A comment is not a mechanism, so it is now derived.
#
# These bodies carry no LINK trailer, so the LINK-side format changes (v4->v5
# slot-direction / Var-payload / CSTRUCT, v5->v6 buffers / LENGTH) do not reach
# them and a version bump alone keeps them valid.
def _binary_repr_version() -> int:
    source = os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        "..", "..", "src", "ir", "binary.rs",
    )
    with open(source, "r", encoding="utf-8") as handle:
        match = re.search(r"BINARY_REPR_VERSION: u16 = (\d+);", handle.read())
    if not match:
        raise SystemExit(
            "could not read BINARY_REPR_VERSION from src/ir/binary.rs — "
            "if the constant was renamed, update this reader rather than "
            "hardcoding a value"
        )
    return int(match.group(1))


BINARY_REPR_VERSION = _binary_repr_version()
from dataclasses import dataclass
from typing import List, Tuple

MFP_MAGIC = bytes([0x4D, 0x46, 0x50, 0x0D, 0x0A, 0x1A, 0x0A, 0x00])
MFPC_MAGIC = b"MFPC"
# Container v1.0 (plan-23 §4): fixed prefix = magic + container/binaryRepr
# versions + flags; the signature block sits at the END of the header and
# signs "MFP-PACKAGE-v2\0" || SHA-256(header bytes before the signature).
HEADER_PREFIX_LEN = 20
SIGNATURE_DOMAIN = b"MFP-PACKAGE-v2\x00"
PROOF_DOMAIN = b"MFP-PROOF-v1\x00"
ATTESTATION_DOMAIN = b"MFP-ATTEST-v1\x00"

# Section ids (mirror src/binary_repr/mod.rs).
SECTION_MANIFEST = 1
SECTION_STRING_POOL = 2
SECTION_TYPE_TABLE = 3
SECTION_CONST_POOL = 4
SECTION_IMPORT_TABLE = 5
SECTION_EXPORT_TABLE = 6
SECTION_GLOBAL_TABLE = 7
SECTION_FUNCTION_TABLE = 8
SECTION_RESOURCE_TABLE = 11
SECTION_ABI_INDEX = 15
SECTION_BINARY_REPR = 16

# Must track `src/binary_repr/mod.rs:FIRST_TABLE_TYPE_ID`. Bumped 10 -> 20 by
# plan-41-B (ids 11-19 are the reserved primitive band; id 10 is now `Scalar`).
FIRST_TABLE_TYPE_ID = 20


def _u16(value: int) -> bytes:
    return struct.pack("<H", value)


def _u32(value: int) -> bytes:
    return struct.pack("<I", value)


def _u64(value: int) -> bytes:
    return struct.pack("<Q", value)


def _read_u16(data: bytes, off: int) -> int:
    return struct.unpack_from("<H", data, off)[0]


def _read_u32(data: bytes, off: int) -> int:
    return struct.unpack_from("<I", data, off)[0]


def _read_u64(data: bytes, off: int) -> int:
    return struct.unpack_from("<Q", data, off)[0]


# --- outer .mfp container ---------------------------------------------------


@dataclass
class MfpContainer:
    """A parsed container v1.0 `.mfp` split into its mutable pieces."""

    header_prefix: bytes  # bytes[..20]: magic, versions, flags
    name: bytes
    ident: bytes
    version: bytes
    author: bytes
    url: bytes
    ident_key: bytes
    signing_key: bytes
    proof: bytes
    proof_sig: bytes
    attestation: bytes
    attestation_sig: bytes
    signature_type: int
    signature: bytes  # 0 or 64 bytes
    binary_repr: bytes  # the inner MFPC payload

    def with_binary_repr(self, binary_repr: bytes) -> "MfpContainer":
        self.binary_repr = binary_repr
        return self

    def signed_prefix(self) -> bytes:
        """Every header byte before the signature itself — what the package
        signature covers. The packageBinaryHash is recomputed from the
        current payload so structural mutators keep a parseable container."""
        out = bytearray()
        out += self.header_prefix
        for field in (
            self.name,
            self.ident,
            self.version,
            self.author,
            self.url,
            self.ident_key,
            self.signing_key,
            self.proof,
            self.proof_sig,
            self.attestation,
            self.attestation_sig,
        ):
            out += _u32(len(field))
            out += field
        out += hashlib.sha256(self.binary_repr).digest()
        out += _u64(len(self.binary_repr))
        out += _u16(self.signature_type)
        out += _u32(len(self.signature))
        return bytes(out)

    def to_bytes(self) -> bytes:
        out = bytearray()
        out += self.signed_prefix()
        out += self.signature
        out += self.binary_repr
        return bytes(out)


def _read_length_prefixed(data: bytes, off: int) -> Tuple[bytes, int]:
    length = _read_u32(data, off)
    off += 4
    value = data[off : off + length]
    off += length
    return value, off


def parse_mfp(data: bytes) -> MfpContainer:
    if data[:8] != MFP_MAGIC:
        raise ValueError("not a .mfp package")
    off = HEADER_PREFIX_LEN
    name, off = _read_length_prefixed(data, off)
    ident, off = _read_length_prefixed(data, off)
    version, off = _read_length_prefixed(data, off)
    author, off = _read_length_prefixed(data, off)
    url, off = _read_length_prefixed(data, off)
    ident_key, off = _read_length_prefixed(data, off)
    signing_key, off = _read_length_prefixed(data, off)
    proof, off = _read_length_prefixed(data, off)
    proof_sig, off = _read_length_prefixed(data, off)
    attestation, off = _read_length_prefixed(data, off)
    attestation_sig, off = _read_length_prefixed(data, off)
    off += 32  # packageBinaryHash (recomputed on re-serialize)
    binary_repr_length = _read_u64(data, off)
    off += 8
    signature_type = _read_u16(data, off)
    signature_length = _read_u32(data, off + 2)
    off += 6
    signature = data[off : off + signature_length]
    off += signature_length
    binary_repr = data[off : off + binary_repr_length]
    return MfpContainer(
        header_prefix=data[:HEADER_PREFIX_LEN],
        name=name,
        ident=ident,
        version=version,
        author=author,
        url=url,
        ident_key=ident_key,
        signing_key=signing_key,
        proof=proof,
        proof_sig=proof_sig,
        attestation=attestation,
        attestation_sig=attestation_sig,
        signature_type=signature_type,
        signature=signature,
        binary_repr=binary_repr,
    )


def _ed25519(private_key_bytes: bytes):
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

    return Ed25519PrivateKey.from_private_bytes(private_key_bytes)


def _public_raw(private_key_bytes: bytes) -> bytes:
    from cryptography.hazmat.primitives import serialization

    return _ed25519(private_key_bytes).public_key().public_bytes(
        serialization.Encoding.Raw, serialization.PublicFormat.Raw
    )


def _b64url(raw: bytes) -> str:
    import base64

    return base64.urlsafe_b64encode(raw).rstrip(b"=").decode("ascii")


def _fingerprint(public_raw: bytes) -> str:
    return hashlib.sha256(public_raw).hexdigest()


def sign_container(
    container: MfpContainer,
    ident_private: bytes,
    server_private: bytes,
    signing_private: bytes,
) -> bytes:
    """Return signed container v1.0 `.mfp` bytes carrying the full plan-23
    trust chain: identKey + one-off signingKey, an ident-signed proof, a
    server-signed attestation, and the prefix signature by the one-off key."""
    ident_public = _public_raw(ident_private)
    signing_public = _public_raw(signing_private)
    server_public = _public_raw(server_private)
    ident_fp = _fingerprint(ident_public)
    signing_fp = _fingerprint(signing_public)
    ident = container.ident.decode("utf-8")
    version = container.version.decode("utf-8")
    owner = ident.split("#", 1)[0]

    proof = (
        f'{{"owner":"{owner}","ident":"{ident}","version":"{version}",'
        f'"identFingerprint":"{ident_fp}","signingFingerprint":"{signing_fp}",'
        f'"issued":1}}'
    ).encode("utf-8")
    proof_sig = _ed25519(ident_private).sign(PROOF_DOMAIN + proof)
    attestation = (
        f'{{"repoFingerprint":"{_fingerprint(server_public)}","owner":"{owner}",'
        f'"ident":"{ident}","version":"{version}",'
        f'"identFingerprint":"{ident_fp}","signingFingerprint":"{signing_fp}",'
        f'"issued":1}}'
    ).encode("utf-8")
    attestation_sig = _ed25519(server_private).sign(ATTESTATION_DOMAIN + attestation)

    container.ident_key = f"ed25519:{_b64url(ident_public)}".encode("ascii")
    container.signing_key = f"ed25519:{_b64url(signing_public)}".encode("ascii")
    container.proof = proof
    container.proof_sig = proof_sig
    container.attestation = attestation
    container.attestation_sig = attestation_sig
    container.signature_type = 1
    container.signature = b"\x00" * 64

    message = SIGNATURE_DOMAIN + hashlib.sha256(container.signed_prefix()).digest()
    signature = _ed25519(signing_private).sign(message)
    assert len(signature) == 64
    container.signature = signature
    return container.to_bytes()


# --- inner MFPC payload -----------------------------------------------------


@dataclass
class MfpcSection:
    id: int
    data: bytes


@dataclass
class Mfpc:
    sections: List[MfpcSection]

    def get(self, section_id: int) -> bytes:
        for section in self.sections:
            if section.id == section_id:
                return section.data
        raise KeyError(section_id)

    def set(self, section_id: int, data: bytes) -> None:
        for section in self.sections:
            if section.id == section_id:
                section.data = data
                return
        raise KeyError(section_id)

    def to_bytes(self) -> bytes:
        table_size = len(self.sections) * 24
        offset = 16 + table_size
        out = bytearray()
        out += MFPC_MAGIC
        out += _u16(2)  # MFPC major
        out += _u16(0)
        out += _u32(0)
        out += _u32(len(self.sections))
        for section in self.sections:
            out += _u16(section.id)
            out += _u16(0)
            out += _u32(0)
            out += _u64(offset)
            out += _u64(len(section.data))
            offset += len(section.data)
        for section in self.sections:
            out += section.data
        return bytes(out)


def parse_mfpc(data: bytes) -> Mfpc:
    if data[:4] != MFPC_MAGIC:
        raise ValueError("not an MFPC payload")
    section_count = _read_u32(data, 12)
    sections: List[MfpcSection] = []
    for i in range(section_count):
        entry = 16 + i * 24
        section_id = _read_u16(data, entry)
        offset = _read_u64(data, entry + 8)
        length = _read_u64(data, entry + 16)
        sections.append(MfpcSection(section_id, data[offset : offset + length]))
    return Mfpc(sections)


def raw_mfpc_with_duplicate_section(mfpc: Mfpc, section_id: int) -> bytes:
    """Re-serialize `mfpc` with a second copy of `section_id` appended, so the
    section table carries a duplicate id (PKG-06)."""
    dup = None
    for section in mfpc.sections:
        if section.id == section_id:
            dup = MfpcSection(section.id, bytes(section.data))
            break
    if dup is None:
        raise KeyError(section_id)
    doubled = Mfpc(list(mfpc.sections) + [dup])
    return doubled.to_bytes()


# --- attack mutators --------------------------------------------------------
#
# Each mutator takes the *unsigned* base `.mfp` bytes (built by `mfb build`) and
# returns the malicious `.mfp` bytes. They operate purely on the on-wire layout,
# so they need no compiler internals.


def mutate_duplicate_section(data: bytes, section_id: int = SECTION_MANIFEST) -> bytes:
    """PKG-06: ship two copies of a singleton MFPC section."""
    container = parse_mfp(data)
    mfpc = parse_mfpc(container.binary_repr)
    container.binary_repr = raw_mfpc_with_duplicate_section(mfpc, section_id)
    return container.to_bytes()


def mutate_cyclic_type(data: bytes) -> bytes:
    """PKG-04: replace the TYPE_TABLE with a single `List` type whose element is
    its own type id, so name decoding recurses forever without a cycle guard."""
    container = parse_mfp(data)
    mfpc = parse_mfpc(container.binary_repr)
    # One entry (kind 4 = List). entries_end = 4 + 1*20 = 24; the 4-byte payload
    # sits right after and encodes the entry's own type id (FIRST_TABLE_TYPE_ID).
    entries_end = 4 + 20
    entry = bytearray()
    entry += _u16(4)  # kind: List
    entry += _u16(0)  # reserved
    entry += _u32(0)  # name string id (0 is always present)
    entry += _u32(0)  # owner package
    entry += _u32(entries_end)  # payload offset
    entry += _u32(4)  # payload length
    payload = _u32(FIRST_TABLE_TYPE_ID)  # element = this very type -> cycle
    type_table = _u32(1) + bytes(entry) + payload
    mfpc.set(SECTION_TYPE_TABLE, type_table)
    container.binary_repr = mfpc.to_bytes()
    return container.to_bytes()


def mutate_string_pool_count(data: bytes, count: int = 0xFFFFFFFF) -> bytes:
    """PKG-05: set the STRING_POOL element count to a huge value behind a tiny
    body. A pre-bounds `Vec::with_capacity(count)` would request gigabytes; the
    bounded reader instead rejects it with a clean truncation error."""
    container = parse_mfp(data)
    mfpc = parse_mfpc(container.binary_repr)
    pool = bytearray(mfpc.get(SECTION_STRING_POOL))
    pool[0:4] = _u32(count)
    mfpc.set(SECTION_STRING_POOL, bytes(pool))
    container.binary_repr = mfpc.to_bytes()
    return container.to_bytes()


def mutate_binary_repr_string_length(data: bytes, length: int = 0xFFFFFFFF) -> bytes:
    """PKG-07: set the first length-prefixed string in the MFBR body (the project
    name) to a huge value. The overflow-safe `IrReader::need` rejects it with a
    clean truncation error instead of wrapping the bound / panicking."""
    container = parse_mfp(data)
    mfpc = parse_mfpc(container.binary_repr)
    body = bytearray(mfpc.get(SECTION_BINARY_REPR))
    # MFBR magic (4) + version (2) then the project-name length u32.
    body[6:10] = _u32(length)
    mfpc.set(SECTION_BINARY_REPR, bytes(body))
    container.binary_repr = mfpc.to_bytes()
    return container.to_bytes()


def mutate_type_confusion(data: bytes) -> bytes:
    """PKG-02: replace the MFBR body with a project whose exported `run` function
    body is type-confused — a `MemberAccess` on an `Integer` constant. The
    package's structured signature tables (unchanged) still declare `run() AS
    Integer`, so the consumer type-checks and links against it; the malicious IR
    only surfaces when the consumer decodes and merges the body for native
    lowering. The IR semantic verifier must reject it before codegen turns the
    member access into an out-of-bounds field load in the victim's binary.

    The body is hand-encoded to mirror `src/ir/binary.rs` (MFBR version 4):
    `MFBR` + u16(BINARY_REPR_VERSION) + project{name, entry=None, bindings=[], types=[],
    functions=[run]}` where `run`'s single op is
    `Return(MemberAccess(target=Const Integer "0", member="x"))`. Format v3
    (plan-20-A/B) appends a `loc` (u32 line + u32 column) to every op and to
    the function declaration, and a result-type string to computed value nodes
    (`MemberAccess` carries `type_` after `member`). The crafted node claims
    type "Integer" — the lie a type-confusion attack would tell — while the
    real violation (member access on an Integer target) is what the verifier
    must catch.
    """
    container = parse_mfp(data)
    mfpc = parse_mfpc(container.binary_repr)

    def put_str(value: bytes) -> bytes:
        return _u32(len(value)) + value

    def put_loc(line: int = 0, column: int = 0) -> bytes:
        return _u32(line) + _u32(column)

    # A `Const { type_: "Integer", value: "0" }` value (tag 0).
    const_int = bytes([0]) + put_str(b"Integer") + put_str(b"0")
    # A `MemberAccess { target: const_int, member: "x", type_: "Integer" }` value (tag 17).
    member_access = bytes([17]) + const_int + put_str(b"x") + put_str(b"Integer")
    # A `Return { value: Some(member_access), loc }` op (tag 3, opt-value present).
    return_op = bytes([3]) + bytes([1]) + member_access + put_loc()
    # The exported `run` function.
    function = bytearray()
    function += put_str(b"run")  # name
    function += put_str(b"export")  # visibility
    function += put_str(b"func")  # kind
    function += bytes([0])  # isolated = false
    function += _u32(0)  # params: none
    function += put_str(b"Integer")  # returns
    function += _u32(1) + return_op  # body: one Return op
    function += put_str(b"")  # source file
    function += put_loc()  # declaration loc (v3)
    function += _u32(0)  # resource_owners: none (v4)

    body = bytearray()
    body += b"MFBR"
    body += _u16(BINARY_REPR_VERSION)  # mirrors src/ir/binary.rs
    body += put_str(b"sec_confused")  # project name
    body += bytes([0])  # entry: None
    body += _u32(0)  # bindings: none
    body += _u32(0)  # types: none
    body += _u32(1) + bytes(function)  # functions: one
    # No native LINK trailer: the body ends after `functions`.
    mfpc.set(SECTION_BINARY_REPR, bytes(body))
    container.binary_repr = mfpc.to_bytes()
    return container.to_bytes()


def mutate_type_confusion_computed(data: bytes) -> bytes:
    """PKG-02b: like `mutate_type_confusion`, but the member access targets a
    *computed* Integer — a `Binary("+", 1, 2)` result — rather than an Integer
    constant. Before the IR carried result types (format v2) the semantic
    checker could not reconstruct a `Binary`'s type and skipped the access; the
    typed IR (v3, plan-20-B) annotates it `Integer`, so plan-20-C's checker
    resolves the target type and rejects the confusion. The crafted `Binary`
    and `MemberAccess` both claim type "Integer" (the attacker's lie); the real
    violation is the member access on that Integer result.

    Body: `run() AS Integer` whose single op is
    `Return(MemberAccess(target=Binary(+, Const 1, Const 2), member="x"))`.
    """
    container = parse_mfp(data)
    mfpc = parse_mfpc(container.binary_repr)

    def put_str(value: bytes) -> bytes:
        return _u32(len(value)) + value

    def put_loc(line: int = 0, column: int = 0) -> bytes:
        return _u32(line) + _u32(column)

    # `Const { type_: "Integer", value: "1"/"2" }` values (tag 0).
    const_one = bytes([0]) + put_str(b"Integer") + put_str(b"1")
    const_two = bytes([0]) + put_str(b"Integer") + put_str(b"2")
    # `Binary { op: "+", left, right, type_: "Integer", loc }` value (tag 18):
    # op string, left value, right value, then the result type and loc (v3).
    binary_add = (
        bytes([18])
        + put_str(b"+")
        + const_one
        + const_two
        + put_str(b"Integer")
        + put_loc()
    )
    # `MemberAccess { target: binary_add, member: "x", type_: "Integer" }` (tag 17).
    member_access = bytes([17]) + binary_add + put_str(b"x") + put_str(b"Integer")
    # `Return { value: Some(member_access), loc }` op (tag 3, opt-value present).
    return_op = bytes([3]) + bytes([1]) + member_access + put_loc()
    # The exported `run` function.
    function = bytearray()
    function += put_str(b"run")  # name
    function += put_str(b"export")  # visibility
    function += put_str(b"func")  # kind
    function += bytes([0])  # isolated = false
    function += _u32(0)  # params: none
    function += put_str(b"Integer")  # returns
    function += _u32(1) + return_op  # body: one Return op
    function += put_str(b"")  # source file
    function += put_loc()  # declaration loc (v3)
    function += _u32(0)  # resource_owners: none (v4)

    body = bytearray()
    body += b"MFBR"
    body += _u16(BINARY_REPR_VERSION)  # mirrors src/ir/binary.rs
    body += put_str(b"sec_confused_computed")  # project name
    body += bytes([0])  # entry: None
    body += _u32(0)  # bindings: none
    body += _u32(0)  # types: none
    body += _u32(1) + bytes(function)  # functions: one
    mfpc.set(SECTION_BINARY_REPR, bytes(body))
    container.binary_repr = mfpc.to_bytes()
    return container.to_bytes()


def mutate_operator_confusion(data: bytes) -> bytes:
    """PKG-02c: replace the MFBR body with a `run` whose IR subtracts a String
    from an Integer — `Return(Binary("-", Const Integer "1", Const String "x"))`.
    The package's signature tables still declare `run() AS Integer`, so the
    consumer links it, but the operand types are incompatible: codegen selects
    the machine instruction from the operand types, so lowering this would emit
    an integer subtract over a String pointer (pointer arithmetic on attacker
    data). The IR operand-type check (plan-20-E) must reject it before codegen.
    The Binary node claims result type "Integer" (the attacker's lie).
    """
    container = parse_mfp(data)
    mfpc = parse_mfpc(container.binary_repr)

    def put_str(value: bytes) -> bytes:
        return _u32(len(value)) + value

    def put_loc(line: int = 0, column: int = 0) -> bytes:
        return _u32(line) + _u32(column)

    const_int = bytes([0]) + put_str(b"Integer") + put_str(b"1")
    const_str = bytes([0]) + put_str(b"String") + put_str(b"x")
    # Binary { op:"-", left:const_int, right:const_str, type_:"Integer", loc } (tag 18).
    binary_sub = (
        bytes([18])
        + put_str(b"-")
        + const_int
        + const_str
        + put_str(b"Integer")
        + put_loc()
    )
    return_op = bytes([3]) + bytes([1]) + binary_sub + put_loc()
    function = bytearray()
    function += put_str(b"run")
    function += put_str(b"export")
    function += put_str(b"func")
    function += bytes([0])
    function += _u32(0)
    function += put_str(b"Integer")
    function += _u32(1) + return_op
    function += put_str(b"")
    function += put_loc()
    function += _u32(0)  # resource_owners: none (v4)

    body = bytearray()
    body += b"MFBR"
    body += _u16(BINARY_REPR_VERSION)
    body += put_str(b"sec_operator_confused")
    body += bytes([0])
    body += _u32(0)
    body += _u32(0)
    body += _u32(1) + bytes(function)
    mfpc.set(SECTION_BINARY_REPR, bytes(body))
    container.binary_repr = mfpc.to_bytes()
    return container.to_bytes()


def mutate_deep_body(data: bytes, depth: int = 300) -> bytes:
    """PKG-03: replace the MFBR body with a minimal project whose single binding
    value is `depth` nested `Unary` expressions, overflowing an unbounded
    recursive decoder. The body aborts decoding at the depth cap before any of
    the trailing (unread) bytes matter."""
    container = parse_mfp(data)
    mfpc = parse_mfpc(container.binary_repr)

    def put_str(value: bytes) -> bytes:
        return _u32(len(value)) + value

    body = bytearray()
    body += MFPC_MAGIC[:0]  # no-op to keep bytearray typed
    body += b"MFBR"
    body += _u16(BINARY_REPR_VERSION)  # mirrors src/ir/binary.rs
    body += put_str(b"x")  # project name
    body += bytes([0])  # entry: None
    body += _u32(1)  # bindings: one
    # binding: name, visibility, mutable, type, then opt-value present.
    body += put_str(b"b")
    body += put_str(b"private")
    body += bytes([0])  # mutable = false
    body += put_str(b"Integer")
    body += bytes([1])  # opt-value present
    # `depth` nested Unary frames (tag 19 + op string). The innermost operand is
    # never read: decoding aborts on entering the over-deep recursion level.
    for _ in range(depth):
        body += bytes([19])
        body += put_str(b"-")
    mfpc.set(SECTION_BINARY_REPR, bytes(body))
    container.binary_repr = mfpc.to_bytes()
    return container.to_bytes()


# --- signing (PKG-01) -------------------------------------------------------
#
# Fixed, test-only Ed25519 private keys so the signed fixtures and the trust
# anchor pinned in the consumer `project.json` are reproducible. NEVER real
# keys — they exist only to make the verification gate demonstrable. Under
# plan-23 the chain needs three: the ident key (the pinned trust anchor), the
# registry server key (signs the attestation), and the one-off signing key.
TEST_PRIVATE_KEY = bytes(range(1, 33))  # ident key: 0x01, 0x02, ... 0x20
TEST_SERVER_PRIVATE_KEY = bytes(range(33, 65))
TEST_SIGNING_PRIVATE_KEY = bytes(range(65, 97))


def test_public_key() -> bytes:
    return _public_raw(TEST_PRIVATE_KEY)


def test_ident_key() -> str:
    """The trust anchor to pin in the consumer `project.json` (`identKey`),
    matching the compiler's `ed25519:<base64url-no-pad>` format."""
    return f"ed25519:{_b64url(test_public_key())}"


def mutate_sign_then_tamper(data: bytes) -> bytes:
    """PKG-01: sign the package with the full test chain, then flip one payload
    byte AFTER signing so the recorded `packageBinaryHash` (inside the signed
    prefix) no longer matches the payload — a tampered signed package the
    verifier must classify Tampered."""
    signed = sign_container(
        parse_mfp(data),
        TEST_PRIVATE_KEY,
        TEST_SERVER_PRIVATE_KEY,
        TEST_SIGNING_PRIVATE_KEY,
    )
    tampered = bytearray(signed)
    # The last byte of the file is inner MFBR body content: flipping it keeps
    # the container parseable but breaks the header→payload hash weld.
    tampered[-1] ^= 0xFF
    return bytes(tampered)


# --- driver helpers ---------------------------------------------------------


def build_base_package(source_dir: str, mfb_bin: str) -> bytes:
    """Build the base package project with `mfb` and return the `.mfp` bytes."""
    import glob
    import os
    import subprocess

    # Remove any stale artifact so we read the fresh build.
    for stale in glob.glob(os.path.join(source_dir, "*.mfp")):
        os.remove(stale)
    subprocess.run([mfb_bin, "build", source_dir], check=True)
    produced = glob.glob(os.path.join(source_dir, "*.mfp"))
    if len(produced) != 1:
        raise RuntimeError(f"expected one .mfp in {source_dir}, found {produced}")
    with open(produced[0], "rb") as handle:
        data = handle.read()
    os.remove(produced[0])
    return data


def write_fixture_package(fixture_dir: str, package_name: str, data: bytes) -> None:
    import os

    packages_dir = os.path.join(fixture_dir, "packages")
    os.makedirs(packages_dir, exist_ok=True)
    path = os.path.join(packages_dir, f"{package_name}.mfp")
    with open(path, "wb") as handle:
        handle.write(data)
    print(f"wrote {path} ({len(data)} bytes)")
