"""Shared helpers for crafting malicious `.mfp` packages (audit-1 fixtures).

The security fixtures under `tests/security/pkg-0*` each import a deliberately
malformed or tampered compiled package to prove the compiler's decode/verify
path rejects it. The malicious `.mfp` files are *generated* (never hand-typed)
by the `generate.py` script that lives next to each source package, using the
primitives in this module. The generated bytes are committed; the scripts exist
for reproducibility and to document exactly how each attack is constructed.

The layout of a `.mfp` container (outer framing) and its inner `MFPC` payload is
described in `src/docs/spec/package/01_container-format.md` and mirrored by the
Rust reader in `src/binary_repr/reader.rs` / `repository/src/package.rs`.

No third-party import is required for the structural mutators. Signing (PKG-01)
uses the standard-library-adjacent `cryptography` package when available; the
committed fixtures were produced with it.
"""

from __future__ import annotations

import hashlib
import struct
from dataclasses import dataclass
from typing import List, Tuple

MFP_MAGIC = bytes([0x4D, 0x46, 0x50, 0x0D, 0x0A, 0x1A, 0x0A, 0x00])
MFPC_MAGIC = b"MFPC"
HEADER_PREFIX_LEN = 26
SIGNATURE_MESSAGE_PREFIX = b"MFP-PACKAGE-v1"

# Section ids (mirror src/binary_repr/mod.rs).
SECTION_MANIFEST = 1
SECTION_STRING_POOL = 2
SECTION_TYPE_TABLE = 3
SECTION_CONST_POOL = 4
SECTION_IMPORT_TABLE = 5
SECTION_EXPORT_TABLE = 6
SECTION_GLOBAL_TABLE = 7
SECTION_FUNCTION_TABLE = 8
SECTION_RESOURCE_TABLE = 11
SECTION_ABI_INDEX = 15
SECTION_BINARY_REPR = 16

FIRST_TABLE_TYPE_ID = 10


def _u16(value: int) -> bytes:
    return struct.pack("<H", value)


def _u32(value: int) -> bytes:
    return struct.pack("<I", value)


def _u64(value: int) -> bytes:
    return struct.pack("<Q", value)


def _read_u16(data: bytes, off: int) -> int:
    return struct.unpack_from("<H", data, off)[0]


def _read_u32(data: bytes, off: int) -> int:
    return struct.unpack_from("<I", data, off)[0]


def _read_u64(data: bytes, off: int) -> int:
    return struct.unpack_from("<Q", data, off)[0]


# --- outer .mfp container ---------------------------------------------------


@dataclass
class MfpContainer:
    """A parsed `.mfp` split into its mutable pieces."""

    header_prefix: bytes  # bytes[..26], including signature_type/length
    signature: bytes  # the raw signature region (0 or 64 bytes)
    name: bytes
    ident: bytes
    version: bytes
    ident_key: bytes
    ident_fingerprint: bytes
    signing_fingerprint: bytes
    author: bytes
    url: bytes
    binary_repr: bytes  # the inner MFPC payload

    @property
    def signature_type(self) -> int:
        return _read_u16(self.header_prefix, 20)

    def with_binary_repr(self, binary_repr: bytes) -> "MfpContainer":
        self.binary_repr = binary_repr
        return self

    def to_bytes(self) -> bytes:
        out = bytearray()
        out += self.header_prefix
        out += self.signature
        for field in (
            self.name,
            self.ident,
            self.version,
            self.ident_key,
            self.ident_fingerprint,
            self.signing_fingerprint,
            self.author,
            self.url,
        ):
            out += _u32(len(field))
            out += field
        out += _u64(len(self.binary_repr))
        out += self.binary_repr
        return bytes(out)


def _read_length_prefixed(data: bytes, off: int) -> Tuple[bytes, int]:
    length = _read_u32(data, off)
    off += 4
    value = data[off : off + length]
    off += length
    return value, off


def parse_mfp(data: bytes) -> MfpContainer:
    if data[:8] != MFP_MAGIC:
        raise ValueError("not a .mfp package")
    signature_length = _read_u32(data, 22)
    off = HEADER_PREFIX_LEN
    signature = data[off : off + signature_length]
    off += signature_length
    name, off = _read_length_prefixed(data, off)
    ident, off = _read_length_prefixed(data, off)
    version, off = _read_length_prefixed(data, off)
    ident_key, off = _read_length_prefixed(data, off)
    ident_fingerprint, off = _read_length_prefixed(data, off)
    signing_fingerprint, off = _read_length_prefixed(data, off)
    author, off = _read_length_prefixed(data, off)
    url, off = _read_length_prefixed(data, off)
    binary_repr_length = _read_u64(data, off)
    off += 8
    binary_repr = data[off : off + binary_repr_length]
    return MfpContainer(
        header_prefix=data[:HEADER_PREFIX_LEN],
        signature=signature,
        name=name,
        ident=ident,
        version=version,
        ident_key=ident_key,
        ident_fingerprint=ident_fingerprint,
        signing_fingerprint=signing_fingerprint,
        author=author,
        url=url,
        binary_repr=binary_repr,
    )


def content_hash(data: bytes) -> bytes:
    """Recompute the signed content hash: header + zeroed signature + rest."""
    signature_length = _read_u32(data, 22)
    signature_end = HEADER_PREFIX_LEN + signature_length
    hasher = hashlib.sha256()
    hasher.update(data[:HEADER_PREFIX_LEN])
    hasher.update(b"\x00" * signature_length)
    hasher.update(data[signature_end:])
    return hasher.digest()


def sign_container(container: MfpContainer, private_key_bytes: bytes) -> bytes:
    """Return signed `.mfp` bytes for `container`, signed with an Ed25519 key."""
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

    key = Ed25519PrivateKey.from_private_bytes(private_key_bytes)

    # Reserve a 64-byte zeroed signature, set signature_type=1/length=64.
    header = bytearray(container.header_prefix)
    header[20:22] = _u16(1)
    header[22:26] = _u32(64)
    container.header_prefix = bytes(header)
    container.signature = b"\x00" * 64
    unsigned = container.to_bytes()

    digest = content_hash(unsigned)
    message = SIGNATURE_MESSAGE_PREFIX + digest + container.ident + container.version
    signature = key.sign(message)
    assert len(signature) == 64
    container.signature = signature
    return container.to_bytes()


# --- inner MFPC payload -----------------------------------------------------


@dataclass
class MfpcSection:
    id: int
    data: bytes


@dataclass
class Mfpc:
    sections: List[MfpcSection]

    def get(self, section_id: int) -> bytes:
        for section in self.sections:
            if section.id == section_id:
                return section.data
        raise KeyError(section_id)

    def set(self, section_id: int, data: bytes) -> None:
        for section in self.sections:
            if section.id == section_id:
                section.data = data
                return
        raise KeyError(section_id)

    def to_bytes(self) -> bytes:
        table_size = len(self.sections) * 24
        offset = 16 + table_size
        out = bytearray()
        out += MFPC_MAGIC
        out += _u16(2)  # MFPC major
        out += _u16(0)
        out += _u32(0)
        out += _u32(len(self.sections))
        for section in self.sections:
            out += _u16(section.id)
            out += _u16(0)
            out += _u32(0)
            out += _u64(offset)
            out += _u64(len(section.data))
            offset += len(section.data)
        for section in self.sections:
            out += section.data
        return bytes(out)


def parse_mfpc(data: bytes) -> Mfpc:
    if data[:4] != MFPC_MAGIC:
        raise ValueError("not an MFPC payload")
    section_count = _read_u32(data, 12)
    sections: List[MfpcSection] = []
    for i in range(section_count):
        entry = 16 + i * 24
        section_id = _read_u16(data, entry)
        offset = _read_u64(data, entry + 8)
        length = _read_u64(data, entry + 16)
        sections.append(MfpcSection(section_id, data[offset : offset + length]))
    return Mfpc(sections)


def raw_mfpc_with_duplicate_section(mfpc: Mfpc, section_id: int) -> bytes:
    """Re-serialize `mfpc` with a second copy of `section_id` appended, so the
    section table carries a duplicate id (PKG-06)."""
    dup = None
    for section in mfpc.sections:
        if section.id == section_id:
            dup = MfpcSection(section.id, bytes(section.data))
            break
    if dup is None:
        raise KeyError(section_id)
    doubled = Mfpc(list(mfpc.sections) + [dup])
    return doubled.to_bytes()


# --- attack mutators --------------------------------------------------------
#
# Each mutator takes the *unsigned* base `.mfp` bytes (built by `mfb build`) and
# returns the malicious `.mfp` bytes. They operate purely on the on-wire layout,
# so they need no compiler internals.


def mutate_duplicate_section(data: bytes, section_id: int = SECTION_MANIFEST) -> bytes:
    """PKG-06: ship two copies of a singleton MFPC section."""
    container = parse_mfp(data)
    mfpc = parse_mfpc(container.binary_repr)
    container.binary_repr = raw_mfpc_with_duplicate_section(mfpc, section_id)
    return container.to_bytes()


def mutate_cyclic_type(data: bytes) -> bytes:
    """PKG-04: replace the TYPE_TABLE with a single `List` type whose element is
    its own type id, so name decoding recurses forever without a cycle guard."""
    container = parse_mfp(data)
    mfpc = parse_mfpc(container.binary_repr)
    # One entry (kind 4 = List). entries_end = 4 + 1*20 = 24; the 4-byte payload
    # sits right after and encodes the entry's own type id (FIRST_TABLE_TYPE_ID).
    entries_end = 4 + 20
    entry = bytearray()
    entry += _u16(4)  # kind: List
    entry += _u16(0)  # reserved
    entry += _u32(0)  # name string id (0 is always present)
    entry += _u32(0)  # owner package
    entry += _u32(entries_end)  # payload offset
    entry += _u32(4)  # payload length
    payload = _u32(FIRST_TABLE_TYPE_ID)  # element = this very type -> cycle
    type_table = _u32(1) + bytes(entry) + payload
    mfpc.set(SECTION_TYPE_TABLE, type_table)
    container.binary_repr = mfpc.to_bytes()
    return container.to_bytes()


def mutate_string_pool_count(data: bytes, count: int = 0xFFFFFFFF) -> bytes:
    """PKG-05: set the STRING_POOL element count to a huge value behind a tiny
    body. A pre-bounds `Vec::with_capacity(count)` would request gigabytes; the
    bounded reader instead rejects it with a clean truncation error."""
    container = parse_mfp(data)
    mfpc = parse_mfpc(container.binary_repr)
    pool = bytearray(mfpc.get(SECTION_STRING_POOL))
    pool[0:4] = _u32(count)
    mfpc.set(SECTION_STRING_POOL, bytes(pool))
    container.binary_repr = mfpc.to_bytes()
    return container.to_bytes()


def mutate_binary_repr_string_length(data: bytes, length: int = 0xFFFFFFFF) -> bytes:
    """PKG-07: set the first length-prefixed string in the MFBR body (the project
    name) to a huge value. The overflow-safe `IrReader::need` rejects it with a
    clean truncation error instead of wrapping the bound / panicking."""
    container = parse_mfp(data)
    mfpc = parse_mfpc(container.binary_repr)
    body = bytearray(mfpc.get(SECTION_BINARY_REPR))
    # MFBR magic (4) + version (2) then the project-name length u32.
    body[6:10] = _u32(length)
    mfpc.set(SECTION_BINARY_REPR, bytes(body))
    container.binary_repr = mfpc.to_bytes()
    return container.to_bytes()


def mutate_deep_body(data: bytes, depth: int = 300) -> bytes:
    """PKG-03: replace the MFBR body with a minimal project whose single binding
    value is `depth` nested `Unary` expressions, overflowing an unbounded
    recursive decoder. The body aborts decoding at the depth cap before any of
    the trailing (unread) bytes matter."""
    container = parse_mfp(data)
    mfpc = parse_mfpc(container.binary_repr)

    def put_str(value: bytes) -> bytes:
        return _u32(len(value)) + value

    body = bytearray()
    body += MFPC_MAGIC[:0]  # no-op to keep bytearray typed
    body += b"MFBR"
    body += _u16(2)  # BINARY_REPR_VERSION
    body += put_str(b"x")  # project name
    body += bytes([0])  # entry: None
    body += _u32(1)  # bindings: one
    # binding: name, visibility, mutable, type, then opt-value present.
    body += put_str(b"b")
    body += put_str(b"private")
    body += bytes([0])  # mutable = false
    body += put_str(b"Integer")
    body += bytes([1])  # opt-value present
    # `depth` nested Unary frames (tag 19 + op string). The innermost operand is
    # never read: decoding aborts on entering the over-deep recursion level.
    for _ in range(depth):
        body += bytes([19])
        body += put_str(b"-")
    mfpc.set(SECTION_BINARY_REPR, bytes(body))
    container.binary_repr = mfpc.to_bytes()
    return container.to_bytes()


# --- signing (PKG-01) -------------------------------------------------------
#
# A fixed, test-only Ed25519 private key so the signed fixtures and the trust
# anchor pinned in the consumer `project.json` are reproducible. NEVER a real
# signing key — it exists only to make the verification gate demonstrable.
TEST_PRIVATE_KEY = bytes(range(1, 33))  # 0x01, 0x02, ... 0x20


def test_public_key() -> bytes:
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
    from cryptography.hazmat.primitives import serialization

    key = Ed25519PrivateKey.from_private_bytes(TEST_PRIVATE_KEY)
    return key.public_key().public_bytes(
        serialization.Encoding.Raw, serialization.PublicFormat.Raw
    )


def test_ident_key() -> str:
    """The trust anchor to pin in the consumer `project.json` (`identKey`),
    matching the compiler's `ed25519:<base64url-no-pad>` format."""
    import base64

    encoded = base64.urlsafe_b64encode(test_public_key()).rstrip(b"=").decode("ascii")
    return f"ed25519:{encoded}"


def mutate_sign_then_tamper(data: bytes) -> bytes:
    """PKG-01: sign the package with the test key, then flip one body byte so the
    recomputed content hash no longer matches the signature — a tampered signed
    package the verifier must classify Tampered."""
    signed = sign_container(parse_mfp(data), TEST_PRIVATE_KEY)
    tampered = bytearray(signed)
    # Flip a byte inside the inner MFBR payload, past the header/signature and
    # every length field, so the container still parses but the content hash
    # differs. The last byte of the file is body content.
    tampered[-1] ^= 0xFF
    return bytes(tampered)


# --- driver helpers ---------------------------------------------------------


def build_base_package(source_dir: str, mfb_bin: str) -> bytes:
    """Build the base package project with `mfb` and return the `.mfp` bytes."""
    import glob
    import os
    import subprocess

    # Remove any stale artifact so we read the fresh build.
    for stale in glob.glob(os.path.join(source_dir, "*.mfp")):
        os.remove(stale)
    subprocess.run([mfb_bin, "build", source_dir], check=True)
    produced = glob.glob(os.path.join(source_dir, "*.mfp"))
    if len(produced) != 1:
        raise RuntimeError(f"expected one .mfp in {source_dir}, found {produced}")
    with open(produced[0], "rb") as handle:
        data = handle.read()
    os.remove(produced[0])
    return data


def write_fixture_package(fixture_dir: str, package_name: str, data: bytes) -> None:
    import os

    packages_dir = os.path.join(fixture_dir, "packages")
    os.makedirs(packages_dir, exist_ok=True)
    path = os.path.join(packages_dir, f"{package_name}.mfp")
    with open(path, "wb") as handle:
        handle.write(data)
    print(f"wrote {path} ({len(data)} bytes)")
