//! Built-in `errorCode` package (plan-06-errorcodes.md): a flat set of `Integer`
//! constants, one per runtime registry row in `specifications/error_codes.md`.
//!
//! This mirrors the `math` constant mechanism (`math::pi` and friends): a
//! reference such as `errorCode::ErrNotFound` types as `Integer` and folds to an
//! integer literal before lowering, so there is no runtime helper, no codegen,
//! and no binary-representation change. Constants are keyed package-qualified
//! (`"errorCode.<Name>"`) exactly like `math.pi`.
//!
//! The constant table is generated from the canonical registry at build time so
//! it cannot drift from the documentation (see `build.rs`).

// Generated by build.rs: `ERRORCODE_CONSTANTS: &[(&str, &str)]` of (Name, integer).
include!(concat!(env!("OUT_DIR"), "/errorcode_generated.rs"));

/// The package-qualified key (`"errorCode.<Name>"`) of a known constant, or
/// `None` for anything else.
fn member(name: &str) -> Option<&str> {
    name.strip_prefix("errorCode.")
}

pub(crate) fn is_errorcode_constant(name: &str) -> bool {
    constant_value(name).is_some()
}

pub(crate) fn constant_type_name(name: &str) -> Option<&'static str> {
    is_errorcode_constant(name).then_some("Integer")
}

pub(crate) fn constant_value(name: &str) -> Option<&'static str> {
    let member = member(name)?;
    ERRORCODE_CONSTANTS
        .iter()
        .find(|(constant_name, _)| *constant_name == member)
        .map(|(_, value)| *value)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The generated table must exactly reproduce the "Runtime and Standard
    /// Package Errors" rows of the canonical registry, with the integer value
    /// equal to the hyphen-stripped `G-SSS-EEEE` code. This is the drift guard
    /// from plan-06-errorcodes.md §6.1.
    #[test]
    fn table_matches_registry() {
        let doc = include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/specifications/error_codes.md"
        ));

        let mut in_section = false;
        let mut rows: Vec<(String, String)> = Vec::new();
        for line in doc.lines() {
            if line.starts_with("## ") {
                in_section = line.contains("Runtime and Standard Package Errors");
                continue;
            }
            if !in_section || !line.trim_start().starts_with("| `") {
                continue;
            }
            let cells: Vec<&str> = line.split('|').map(str::trim).collect();
            if cells.len() < 4 {
                continue;
            }
            let code = cells[1].trim_matches('`');
            let integer = cells[2].trim_matches('`');
            let name = cells[3].trim_matches('`');
            if code.is_empty() || integer.is_empty() || name.is_empty() {
                continue;
            }
            assert_eq!(
                code.replace('-', ""),
                integer,
                "registry row `{name}`: code `{code}` != integer `{integer}`",
            );
            rows.push((name.to_string(), integer.to_string()));
        }

        assert!(!rows.is_empty(), "no registry rows parsed");

        let generated: Vec<(String, String)> = ERRORCODE_CONSTANTS
            .iter()
            .map(|(name, value)| (name.to_string(), value.to_string()))
            .collect();
        assert_eq!(
            generated, rows,
            "generated errorCode table does not match error_codes.md",
        );

        // Every exported constant resolves through the package-qualified API.
        for (name, value) in ERRORCODE_CONSTANTS {
            let key = format!("errorCode.{name}");
            assert!(is_errorcode_constant(&key), "`{key}` not recognized");
            assert_eq!(constant_type_name(&key), Some("Integer"));
            assert_eq!(constant_value(&key), Some(*value));
        }
    }

    #[test]
    fn spec_example_values() {
        // The concrete examples standard_package.md §13 and plan §6.2 call out.
        assert_eq!(constant_value("errorCode.ErrNotFound"), Some("77050004"));
        assert_eq!(
            constant_value("errorCode.ErrInvalidArgument"),
            Some("77050002")
        );
    }

    #[test]
    fn rejects_unknown_and_unqualified() {
        assert!(!is_errorcode_constant("errorCode.NotARealName"));
        assert!(!is_errorcode_constant("ErrNotFound"));
        assert!(!is_errorcode_constant("math.pi"));
        assert_eq!(constant_value("errorCode.NotARealName"), None);
    }
}
