#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum CodeOp {
    Label,
    Mov,
    MovImm,
    Add,
    Sub,
    UDiv,
    MSub,
    AddImm,
    SubImm,
    SubSp,
    AddSp,
    CmpImm,
    Cmp,
    BranchEq,
    BranchNe,
    BranchGe,
    BranchHi,
    BranchLo,
    Branch,
    BranchLink,
    BranchSelf,
    Svc,
    Ret,
    LdrU64,
    StrU64,
    StrU8,
    Adrp,
    AddPageOff,
}

impl CodeOp {
    pub(crate) fn mnemonic(self) -> &'static str {
        match self {
            CodeOp::Label => "label",
            CodeOp::Mov => "mov",
            CodeOp::MovImm => "mov_imm",
            CodeOp::Add => "add",
            CodeOp::Sub => "sub",
            CodeOp::UDiv => "udiv",
            CodeOp::MSub => "msub",
            CodeOp::AddImm => "add_imm",
            CodeOp::SubImm => "sub_imm",
            CodeOp::SubSp => "sub_sp",
            CodeOp::AddSp => "add_sp",
            CodeOp::CmpImm => "cmp_imm",
            CodeOp::Cmp => "cmp",
            CodeOp::BranchEq => "b.eq",
            CodeOp::BranchNe => "b.ne",
            CodeOp::BranchGe => "b.ge",
            CodeOp::BranchHi => "b.hi",
            CodeOp::BranchLo => "b.lo",
            CodeOp::Branch => "b",
            CodeOp::BranchLink => "bl",
            CodeOp::BranchSelf => "branch_self",
            CodeOp::Svc => "svc",
            CodeOp::Ret => "ret",
            CodeOp::LdrU64 => "ldr_u64",
            CodeOp::StrU64 => "str_u64",
            CodeOp::StrU8 => "str_u8",
            CodeOp::Adrp => "adrp",
            CodeOp::AddPageOff => "add_pageoff",
        }
    }

    pub(crate) fn from_mnemonic(op: &str) -> Result<Self, String> {
        match op {
            "label" => Ok(CodeOp::Label),
            "mov" => Ok(CodeOp::Mov),
            "mov_imm" => Ok(CodeOp::MovImm),
            "add" => Ok(CodeOp::Add),
            "sub" => Ok(CodeOp::Sub),
            "udiv" => Ok(CodeOp::UDiv),
            "msub" => Ok(CodeOp::MSub),
            "add_imm" => Ok(CodeOp::AddImm),
            "sub_imm" => Ok(CodeOp::SubImm),
            "sub_sp" => Ok(CodeOp::SubSp),
            "add_sp" => Ok(CodeOp::AddSp),
            "cmp_imm" => Ok(CodeOp::CmpImm),
            "cmp" => Ok(CodeOp::Cmp),
            "b.eq" => Ok(CodeOp::BranchEq),
            "b.ne" => Ok(CodeOp::BranchNe),
            "b.ge" => Ok(CodeOp::BranchGe),
            "b.hi" => Ok(CodeOp::BranchHi),
            "b.lo" => Ok(CodeOp::BranchLo),
            "b" => Ok(CodeOp::Branch),
            "bl" => Ok(CodeOp::BranchLink),
            "branch_self" => Ok(CodeOp::BranchSelf),
            "svc" => Ok(CodeOp::Svc),
            "ret" => Ok(CodeOp::Ret),
            "ldr_u64" => Ok(CodeOp::LdrU64),
            "str_u64" => Ok(CodeOp::StrU64),
            "str_u8" => Ok(CodeOp::StrU8),
            "adrp" => Ok(CodeOp::Adrp),
            "add_pageoff" => Ok(CodeOp::AddPageOff),
            other => Err(format!("aarch64 code op '{other}' is not encodable")),
        }
    }
}
