#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum CodeOp {
    Label,
    Mov,
    MovImm,
    Add,
    Adds,
    Sub,
    Subs,
    And,
    Orr,
    Eor,
    Mvn,
    Mul,
    SMulH,
    UMulH,
    Adc,
    Rorv,
    RorvW,
    Lslv,
    Lsrv,
    Asrv,
    Clz,
    Rbit,
    RevW,
    RevX,
    SDiv,
    UDiv,
    MSub,
    LslImm,
    LsrImm,
    AsrImm,
    AddImm,
    SubImm,
    SubSp,
    AddSp,
    CmpImm,
    Cmp,
    BranchEq,
    BranchNe,
    BranchGe,
    BranchLt,
    BranchGt,
    BranchLe,
    BranchVc,
    /// `b.vs` — branch if the overflow flag is set. After `fcmp`, V is set on an
    /// unordered (NaN) result, so this is the FP-domain non-finite NaN check
    /// (plan-16 Piece B).
    BranchVs,
    BranchHi,
    BranchLo,
    /// `b.mi` — branch if N (negative) is set. After `fcmp` an ordered
    /// less-than sets N and every other ordered relation (and an unordered NaN)
    /// clears it, so this is the IEEE float `<` (unordered ⇒ false; plan-17).
    BranchMi,
    /// `b.ls` — branch if C clear or Z set. After `fcmp` an ordered less-than
    /// (C=0) or equal (Z=1) takes it while greater and unordered (C=1, Z=0) do
    /// not, so this is the IEEE float `<=` (unordered ⇒ false; plan-17).
    BranchLs,
    Branch,
    BranchLink,
    BranchLinkRegister,
    BranchSelf,
    Svc,
    Ret,
    LdrU64,
    LdrU32,
    LdrU16,
    LdrU8,
    StrU64,
    StrU32,
    StrU8,
    /// 64-bit FP scalar load/store (`ldr d`/`str d`), used to spill and reload an
    /// FP-class virtual register (plan-03 Stage C).
    LdrD,
    StrD,
    Adrp,
    AddPageOff,
    FMovXFromD,
    FMovDFromX,
    /// `fmov Dd, Dn` — move one scalar `d`-register into another, used to update a
    /// loop-promoted float local's resident register (plan-03 Stage D).
    FMovDFromD,
    FAddD,
    FSubD,
    FMulD,
    FDivD,
    FNegD,
    /// `fabs Dd, Dn` — scalar double absolute value, used by the FP-domain
    /// finiteness check to fold ±Inf together before the `fcmp` (plan-16 Piece B).
    FAbsD,
    FSqrtD,
    FCmpD,
    FCmpZeroD,
    SCvtfDFromX,
    FCvtzsXFromD,
    FCvtmsXFromD,
    FCvtpsXFromD,
    FCvtasXFromD,
    // --- NEON vector ops (plan-01-simd Phase 1) ---
    // 128-bit vector load/store.
    LdrQ,
    StrQ,
    // FP three-same `.2d` (two f64 lanes).
    FAddV,
    FSubV,
    FMulV,
    FDivV,
    FMlaV,
    FMlsV,
    FMinV,
    FMaxV,
    FCmGtV,
    FCmGeV,
    FCmEqV,
    // FP two-reg-misc `.2d`.
    FAbsV,
    FNegV,
    FSqrtV,
    FRintpV,
    FRintmV,
    FRintaV,
    FRintnV,
    FRintzV,
    FCvtzsV,
    FCvtasV,
    ScvtfV,
    // FP compare-against-zero `.2d`.
    FCmGtZeroV,
    FCmGeZeroV,
    FCmEqZeroV,
    FCmLtZeroV,
    FCmLeZeroV,
    // Integer three-same `.2d` (two i64 lanes).
    AddV,
    SubV,
    CmGtV,
    CmGeV,
    CmEqV,
    SshlV,
    UshlV,
    // Integer two-reg-misc `.2d`.
    NegV,
    AbsV,
    // Bitwise three-same `.16b`.
    AndV,
    OrrV,
    EorV,
    BslV,
    BitV,
    // Shifted-immediate `.2d`.
    ShlV,
    SshrV,
    UshrV,
    // Lane broadcast / extract.
    DupVFromX,
    UmovXFromV,
    /// Scalar fused multiply-add: `Dd = Da + Dn*Dm` (round once). Used by the
    /// Float transcendental kernels' scalar tail so it is bit-identical to the
    /// vector `fmla_v` Horner steps (plan-01-simd §4.6).
    FMaddD,
}

impl CodeOp {
    pub(crate) fn mnemonic(self) -> &'static str {
        match self {
            CodeOp::Label => "label",
            CodeOp::Mov => "mov",
            CodeOp::MovImm => "mov_imm",
            CodeOp::Add => "add",
            CodeOp::Adds => "adds",
            CodeOp::Sub => "sub",
            CodeOp::Subs => "subs",
            CodeOp::And => "and",
            CodeOp::Orr => "orr",
            CodeOp::Eor => "eor",
            CodeOp::Mvn => "mvn",
            CodeOp::Mul => "mul",
            CodeOp::SMulH => "smulh",
            CodeOp::UMulH => "umulh",
            CodeOp::Adc => "adc",
            CodeOp::Rorv => "rorv",
            CodeOp::RorvW => "rorv_w",
            CodeOp::Lslv => "lslv",
            CodeOp::Lsrv => "lsrv",
            CodeOp::Asrv => "asrv",
            CodeOp::Clz => "clz",
            CodeOp::Rbit => "rbit",
            CodeOp::RevW => "rev_w",
            CodeOp::RevX => "rev_x",
            CodeOp::SDiv => "sdiv",
            CodeOp::UDiv => "udiv",
            CodeOp::MSub => "msub",
            CodeOp::LslImm => "lsl_imm",
            CodeOp::LsrImm => "lsr_imm",
            CodeOp::AsrImm => "asr_imm",
            CodeOp::AddImm => "add_imm",
            CodeOp::SubImm => "sub_imm",
            CodeOp::SubSp => "sub_sp",
            CodeOp::AddSp => "add_sp",
            CodeOp::CmpImm => "cmp_imm",
            CodeOp::Cmp => "cmp",
            CodeOp::BranchEq => "b.eq",
            CodeOp::BranchNe => "b.ne",
            CodeOp::BranchGe => "b.ge",
            CodeOp::BranchLt => "b.lt",
            CodeOp::BranchGt => "b.gt",
            CodeOp::BranchLe => "b.le",
            CodeOp::BranchVc => "b.vc",
            CodeOp::BranchVs => "b.vs",
            CodeOp::BranchHi => "b.hi",
            CodeOp::BranchLo => "b.lo",
            CodeOp::BranchMi => "b.mi",
            CodeOp::BranchLs => "b.ls",
            CodeOp::Branch => "b",
            CodeOp::BranchLink => "bl",
            CodeOp::BranchLinkRegister => "blr",
            CodeOp::BranchSelf => "branch_self",
            CodeOp::Svc => "svc",
            CodeOp::Ret => "ret",
            CodeOp::LdrU64 => "ldr_u64",
            CodeOp::LdrU32 => "ldr_u32",
            CodeOp::LdrU16 => "ldr_u16",
            CodeOp::LdrU8 => "ldr_u8",
            CodeOp::StrU64 => "str_u64",
            CodeOp::StrU32 => "str_u32",
            CodeOp::StrU8 => "str_u8",
            CodeOp::LdrD => "ldr_d",
            CodeOp::StrD => "str_d",
            CodeOp::Adrp => "adrp",
            CodeOp::AddPageOff => "add_pageoff",
            CodeOp::FMovXFromD => "fmov_x_from_d",
            CodeOp::FMovDFromX => "fmov_d_from_x",
            CodeOp::FMovDFromD => "fmov_d_from_d",
            CodeOp::FAddD => "fadd_d",
            CodeOp::FSubD => "fsub_d",
            CodeOp::FMulD => "fmul_d",
            CodeOp::FDivD => "fdiv_d",
            CodeOp::FNegD => "fneg_d",
            CodeOp::FAbsD => "fabs_d",
            CodeOp::FSqrtD => "fsqrt_d",
            CodeOp::FCmpD => "fcmp_d",
            CodeOp::FCmpZeroD => "fcmp_zero_d",
            CodeOp::SCvtfDFromX => "scvtf_d_from_x",
            CodeOp::FCvtzsXFromD => "fcvtzs_x_from_d",
            CodeOp::FCvtmsXFromD => "fcvtms_x_from_d",
            CodeOp::FCvtpsXFromD => "fcvtps_x_from_d",
            CodeOp::FCvtasXFromD => "fcvtas_x_from_d",
            CodeOp::LdrQ => "ldr_q",
            CodeOp::StrQ => "str_q",
            CodeOp::FAddV => "fadd_v",
            CodeOp::FSubV => "fsub_v",
            CodeOp::FMulV => "fmul_v",
            CodeOp::FDivV => "fdiv_v",
            CodeOp::FMlaV => "fmla_v",
            CodeOp::FMlsV => "fmls_v",
            CodeOp::FMinV => "fmin_v",
            CodeOp::FMaxV => "fmax_v",
            CodeOp::FCmGtV => "fcmgt_v",
            CodeOp::FCmGeV => "fcmge_v",
            CodeOp::FCmEqV => "fcmeq_v",
            CodeOp::FAbsV => "fabs_v",
            CodeOp::FNegV => "fneg_v",
            CodeOp::FSqrtV => "fsqrt_v",
            CodeOp::FRintpV => "frintp_v",
            CodeOp::FRintmV => "frintm_v",
            CodeOp::FRintaV => "frinta_v",
            CodeOp::FRintnV => "frintn_v",
            CodeOp::FRintzV => "frintz_v",
            CodeOp::FCvtzsV => "fcvtzs_v",
            CodeOp::FCvtasV => "fcvtas_v",
            CodeOp::ScvtfV => "scvtf_v",
            CodeOp::FCmGtZeroV => "fcmgt_zero_v",
            CodeOp::FCmGeZeroV => "fcmge_zero_v",
            CodeOp::FCmEqZeroV => "fcmeq_zero_v",
            CodeOp::FCmLtZeroV => "fcmlt_zero_v",
            CodeOp::FCmLeZeroV => "fcmle_zero_v",
            CodeOp::AddV => "add_v",
            CodeOp::SubV => "sub_v",
            CodeOp::CmGtV => "cmgt_v",
            CodeOp::CmGeV => "cmge_v",
            CodeOp::CmEqV => "cmeq_v",
            CodeOp::SshlV => "sshl_v",
            CodeOp::UshlV => "ushl_v",
            CodeOp::NegV => "neg_v",
            CodeOp::AbsV => "abs_v",
            CodeOp::AndV => "and_v",
            CodeOp::OrrV => "orr_v",
            CodeOp::EorV => "eor_v",
            CodeOp::BslV => "bsl_v",
            CodeOp::BitV => "bit_v",
            CodeOp::ShlV => "shl_v",
            CodeOp::SshrV => "sshr_v",
            CodeOp::UshrV => "ushr_v",
            CodeOp::DupVFromX => "dup_v_from_x",
            CodeOp::UmovXFromV => "umov_x_from_v",
            CodeOp::FMaddD => "fmadd_d",
        }
    }

    pub(crate) fn from_mnemonic(op: &str) -> Result<Self, String> {
        match op {
            "label" => Ok(CodeOp::Label),
            "mov" => Ok(CodeOp::Mov),
            "mov_imm" => Ok(CodeOp::MovImm),
            "add" => Ok(CodeOp::Add),
            "adds" => Ok(CodeOp::Adds),
            "sub" => Ok(CodeOp::Sub),
            "subs" => Ok(CodeOp::Subs),
            "and" => Ok(CodeOp::And),
            "orr" => Ok(CodeOp::Orr),
            "eor" => Ok(CodeOp::Eor),
            "mvn" => Ok(CodeOp::Mvn),
            "mul" => Ok(CodeOp::Mul),
            "smulh" => Ok(CodeOp::SMulH),
            "umulh" => Ok(CodeOp::UMulH),
            "adc" => Ok(CodeOp::Adc),
            "rorv" => Ok(CodeOp::Rorv),
            "rorv_w" => Ok(CodeOp::RorvW),
            "lslv" => Ok(CodeOp::Lslv),
            "lsrv" => Ok(CodeOp::Lsrv),
            "asrv" => Ok(CodeOp::Asrv),
            "clz" => Ok(CodeOp::Clz),
            "rbit" => Ok(CodeOp::Rbit),
            "rev_w" => Ok(CodeOp::RevW),
            "rev_x" => Ok(CodeOp::RevX),
            "sdiv" => Ok(CodeOp::SDiv),
            "udiv" => Ok(CodeOp::UDiv),
            "msub" => Ok(CodeOp::MSub),
            "lsl_imm" => Ok(CodeOp::LslImm),
            "lsr_imm" => Ok(CodeOp::LsrImm),
            "asr_imm" => Ok(CodeOp::AsrImm),
            "add_imm" => Ok(CodeOp::AddImm),
            "sub_imm" => Ok(CodeOp::SubImm),
            "sub_sp" => Ok(CodeOp::SubSp),
            "add_sp" => Ok(CodeOp::AddSp),
            "cmp_imm" => Ok(CodeOp::CmpImm),
            "cmp" => Ok(CodeOp::Cmp),
            "b.eq" => Ok(CodeOp::BranchEq),
            "b.ne" => Ok(CodeOp::BranchNe),
            "b.ge" => Ok(CodeOp::BranchGe),
            "b.lt" => Ok(CodeOp::BranchLt),
            "b.gt" => Ok(CodeOp::BranchGt),
            "b.le" => Ok(CodeOp::BranchLe),
            "b.vc" => Ok(CodeOp::BranchVc),
            "b.vs" => Ok(CodeOp::BranchVs),
            "b.hi" => Ok(CodeOp::BranchHi),
            "b.lo" => Ok(CodeOp::BranchLo),
            "b.mi" => Ok(CodeOp::BranchMi),
            "b.ls" => Ok(CodeOp::BranchLs),
            "b" => Ok(CodeOp::Branch),
            "bl" => Ok(CodeOp::BranchLink),
            "blr" => Ok(CodeOp::BranchLinkRegister),
            "branch_self" => Ok(CodeOp::BranchSelf),
            "svc" => Ok(CodeOp::Svc),
            "ret" => Ok(CodeOp::Ret),
            "ldr_u64" => Ok(CodeOp::LdrU64),
            "ldr_u32" => Ok(CodeOp::LdrU32),
            "ldr_u16" => Ok(CodeOp::LdrU16),
            "ldr_u8" => Ok(CodeOp::LdrU8),
            "str_u64" => Ok(CodeOp::StrU64),
            "str_u32" => Ok(CodeOp::StrU32),
            "str_u8" => Ok(CodeOp::StrU8),
            "ldr_d" => Ok(CodeOp::LdrD),
            "str_d" => Ok(CodeOp::StrD),
            "adrp" => Ok(CodeOp::Adrp),
            "add_pageoff" => Ok(CodeOp::AddPageOff),
            "fmov_x_from_d" => Ok(CodeOp::FMovXFromD),
            "fmov_d_from_x" => Ok(CodeOp::FMovDFromX),
            "fmov_d_from_d" => Ok(CodeOp::FMovDFromD),
            "fadd_d" => Ok(CodeOp::FAddD),
            "fsub_d" => Ok(CodeOp::FSubD),
            "fmul_d" => Ok(CodeOp::FMulD),
            "fdiv_d" => Ok(CodeOp::FDivD),
            "fneg_d" => Ok(CodeOp::FNegD),
            "fabs_d" => Ok(CodeOp::FAbsD),
            "fsqrt_d" => Ok(CodeOp::FSqrtD),
            "fcmp_d" => Ok(CodeOp::FCmpD),
            "fcmp_zero_d" => Ok(CodeOp::FCmpZeroD),
            "scvtf_d_from_x" => Ok(CodeOp::SCvtfDFromX),
            "fcvtzs_x_from_d" => Ok(CodeOp::FCvtzsXFromD),
            "fcvtms_x_from_d" => Ok(CodeOp::FCvtmsXFromD),
            "fcvtps_x_from_d" => Ok(CodeOp::FCvtpsXFromD),
            "fcvtas_x_from_d" => Ok(CodeOp::FCvtasXFromD),
            "ldr_q" => Ok(CodeOp::LdrQ),
            "str_q" => Ok(CodeOp::StrQ),
            "fadd_v" => Ok(CodeOp::FAddV),
            "fsub_v" => Ok(CodeOp::FSubV),
            "fmul_v" => Ok(CodeOp::FMulV),
            "fdiv_v" => Ok(CodeOp::FDivV),
            "fmla_v" => Ok(CodeOp::FMlaV),
            "fmls_v" => Ok(CodeOp::FMlsV),
            "fmin_v" => Ok(CodeOp::FMinV),
            "fmax_v" => Ok(CodeOp::FMaxV),
            "fcmgt_v" => Ok(CodeOp::FCmGtV),
            "fcmge_v" => Ok(CodeOp::FCmGeV),
            "fcmeq_v" => Ok(CodeOp::FCmEqV),
            "fabs_v" => Ok(CodeOp::FAbsV),
            "fneg_v" => Ok(CodeOp::FNegV),
            "fsqrt_v" => Ok(CodeOp::FSqrtV),
            "frintp_v" => Ok(CodeOp::FRintpV),
            "frintm_v" => Ok(CodeOp::FRintmV),
            "frinta_v" => Ok(CodeOp::FRintaV),
            "frintn_v" => Ok(CodeOp::FRintnV),
            "frintz_v" => Ok(CodeOp::FRintzV),
            "fcvtzs_v" => Ok(CodeOp::FCvtzsV),
            "fcvtas_v" => Ok(CodeOp::FCvtasV),
            "scvtf_v" => Ok(CodeOp::ScvtfV),
            "fcmgt_zero_v" => Ok(CodeOp::FCmGtZeroV),
            "fcmge_zero_v" => Ok(CodeOp::FCmGeZeroV),
            "fcmeq_zero_v" => Ok(CodeOp::FCmEqZeroV),
            "fcmlt_zero_v" => Ok(CodeOp::FCmLtZeroV),
            "fcmle_zero_v" => Ok(CodeOp::FCmLeZeroV),
            "add_v" => Ok(CodeOp::AddV),
            "sub_v" => Ok(CodeOp::SubV),
            "cmgt_v" => Ok(CodeOp::CmGtV),
            "cmge_v" => Ok(CodeOp::CmGeV),
            "cmeq_v" => Ok(CodeOp::CmEqV),
            "sshl_v" => Ok(CodeOp::SshlV),
            "ushl_v" => Ok(CodeOp::UshlV),
            "neg_v" => Ok(CodeOp::NegV),
            "abs_v" => Ok(CodeOp::AbsV),
            "and_v" => Ok(CodeOp::AndV),
            "orr_v" => Ok(CodeOp::OrrV),
            "eor_v" => Ok(CodeOp::EorV),
            "bsl_v" => Ok(CodeOp::BslV),
            "bit_v" => Ok(CodeOp::BitV),
            "shl_v" => Ok(CodeOp::ShlV),
            "sshr_v" => Ok(CodeOp::SshrV),
            "ushr_v" => Ok(CodeOp::UshrV),
            "dup_v_from_x" => Ok(CodeOp::DupVFromX),
            "umov_x_from_v" => Ok(CodeOp::UmovXFromV),
            "fmadd_d" => Ok(CodeOp::FMaddD),
            other => Err(format!("aarch64 code op '{other}' is not encodable")),
        }
    }
}
