//! `canvas::createImage` — build an `Image` from raw RGBA8 pixels.

// --- codegen tier imports (migration) ---
use crate::codegen::app::hook::app::{prepend_wrong_mode_gate, ModeRequirement};
use crate::codegen::engine::builder::*;
use crate::codegen::engine::operand::Operand;
use crate::codegen::error::constants::*;
use crate::codegen::registry::{
    AbiCtx, Body, DefaultValue, Implementation, Parameter, RegistryFunction, RegistryPackage,
};
use crate::target::shared::abi;
use crate::types::ParameterType;

use super::gen_image::*;

const INTRO: &str = r#"Create an `Image` from raw RGBA8 pixel bytes."#;

const DESC: &str = r#"`createImage` builds an image from pixels the program already has — decoded by it,
generated by it, or read from a file it parsed itself. `pixels` is RGBA8 in row
order, top row first, so it must be exactly `width * height * 4` bytes; any other
length raises `ErrBadPixelCount` rather than reading past the end or silently
padding.

The pixels are **copied**. The runtime keeps its own copy as the image's contents,
so you are free to reuse or discard the list immediately, and
`canvas::getBytes` can answer later without asking the backend for anything.

The result is a resource; it closes itself when its binding goes out of scope, or when
`canvas::destroyImage` is called. Drawing it means putting a `canvas::imageRef` of
it in a `Picture` item — the scene carries the id, not the image, so destroying an
image a scene still names is safe.

Requires `Mode.Canvas`; elsewhere it raises the trappable `ErrWrongMode`."#;

const EX: &str = r#"A 2×1 image — one opaque red pixel, one opaque blue — drawn scaled up. A list
literal does not span source lines, so the pixels go on one:

```
IMPORT app
IMPORT canvas

SUB main()
  app::setMode(Mode.Canvas)
  LET px AS List OF Byte = [toByte(255), toByte(0), toByte(0), toByte(255), toByte(0), toByte(0), toByte(255), toByte(255)]
  RES img AS canvas::Image = canvas::createImage(2, 1, px)
  LET tile AS DrawItem = Picture[x := 0.0, y := 0.0, w := 64.0, h := 32.0, image := canvas::imageRef(img), paint := canvas::fill(canvas::rgb(255, 255, 255))]
  canvas::present([tile])
END SUB
```"#;

/// `canvas::createImage(width, height, pixels)`.
///
/// The size check is `len(pixels) == width * height * 4`, done with a **checked**
/// multiply: `width` and `height` arrive as `Integer`, so a caller can pass values
/// whose product overflows 64 bits, and an unchecked multiply would wrap to a small
/// number that a short list then "matches". Negative extents are rejected by the
/// same comparison — a negative product cannot equal a length.
pub(crate) fn lower_create_image(
    builder: &mut CodeBuilder,
    args: &[ValueResult],
    ctx: &AbiCtx,
) -> Result<ValueResult, String> {
    let symbol = builder.current_symbol.clone();
    if args.len() < 3 {
        return Err(format!("'{symbol}' expects width, height and pixels"));
    }
    let width_in = args[0].location.clone();
    let height_in = args[1].location.clone();
    let pixels_in = args[2].location.clone();

    let bad_count = builder.label("canvas_create_image_bad_count");
    let alloc_ok = builder.label("canvas_create_image_alloc_ok");
    let done = builder.label("canvas_create_image_done");

    // Park the three arguments: every call below clobbers the argument registers.
    let width_slot = builder.allocate_stack_object("canvas_image_width", 8);
    let height_slot = builder.allocate_stack_object("canvas_image_height", 8);
    let pixels_slot = builder.allocate_stack_object("canvas_image_pixels", 8);
    builder.emit(abi::store_u64(&width_in, abi::stack_pointer(), width_slot));
    builder.emit(abi::store_u64(
        &height_in,
        abi::stack_pointer(),
        height_slot,
    ));
    builder.emit(abi::store_u64(
        &pixels_in,
        abi::stack_pointer(),
        pixels_slot,
    ));

    // expected = width * height * 4, rejecting an overflowing or negative product.
    let width = builder.temporary_vreg();
    let height = builder.temporary_vreg();
    let expected = builder.temporary_vreg();
    builder.emit(abi::load_u64(&width, abi::stack_pointer(), width_slot));
    builder.emit(abi::load_u64(&height, abi::stack_pointer(), height_slot));
    builder.emit_checked_size_multiply(&expected, &width, &height, &bad_count);
    let bpp = builder.temporary_vreg();
    builder.emit(abi::move_immediate(
        &bpp,
        "Integer",
        &BYTES_PER_PIXEL.to_string(),
    ));
    let expected_bytes = builder.temporary_vreg();
    builder.emit_checked_size_multiply(&expected_bytes, &expected, &bpp, &bad_count);

    // actual = pixels.count
    let pixels = builder.temporary_vreg();
    let actual = builder.temporary_vreg();
    builder.emit(abi::load_u64(&pixels, abi::stack_pointer(), pixels_slot));
    builder.emit(abi::load_u64(&actual, &pixels, COLLECTION_OFFSET_COUNT));
    builder.emit(abi::compare_registers(&actual, &expected_bytes));
    builder.emit(abi::branch_ne(&bad_count));

    // Copy the pixels into runtime-owned storage. `copy_flat_block` on a collection
    // is shrink-to-fit, so the shadow carries no caller headroom.
    let pixel_type = ParameterType::list_of(ParameterType::Byte);
    let pixels_again = builder.temporary_vreg();
    builder.emit(abi::load_u64(
        &pixels_again,
        abi::stack_pointer(),
        pixels_slot,
    ));
    let shadow = builder.copy_flat_block(&pixel_type, &pixels_again)?;
    let shadow_slot = builder.allocate_stack_object("canvas_image_shadow", 8);
    builder.emit(abi::store_u64(&shadow, abi::stack_pointer(), shadow_slot));

    // Allocate and stamp the resource record.
    builder.emit(abi::move_immediate(
        abi::c_arg(0),
        "Integer",
        RESOURCE_RECORD_SIZE,
    ));
    builder.emit(abi::move_immediate(abi::c_arg(1), "Integer", "8"));
    builder.emit_arena_alloc_call();
    builder.emit(abi::branch_eq(&alloc_ok));
    builder.raise_error_bare("ErrOutOfMemory")?;
    builder.emit(abi::branch(&done));
    builder.emit(abi::label(&alloc_ok));

    let record = builder.temporary_vreg();
    builder.emit(abi::move_register(&record, abi::mfb_return(1)));
    let scratch = builder.temporary_vreg();
    builder.emit(abi::move_immediate(&scratch, "Integer", RESOURCE_TAG_IMAGE));
    builder.emit(abi::store_u64(&scratch, &record, RESOURCE_OFFSET_TAG));
    // `handle@8` is the backend id. Until a backend exists (plan-98-C/E/F) it is the
    // record's own address, which is already unique and non-zero for the lifetime of
    // the image — so an `ImageRef` is a real, distinguishable identity from the
    // start rather than a placeholder, and the backend can adopt it as its key.
    builder.emit(abi::store_u64(&record, &record, RESOURCE_OFFSET_HANDLE));
    builder.emit(abi::store_u64(abi::ZERO, &record, RESOURCE_OFFSET_CLOSED));
    builder.emit(abi::store_u64(abi::ZERO, &record, RESOURCE_OFFSET_STATE));
    let value = builder.temporary_vreg();
    builder.emit(abi::load_u64(&value, abi::stack_pointer(), width_slot));
    builder.emit(abi::store_u64(&value, &record, IMAGE_WIDTH));
    builder.emit(abi::load_u64(&value, abi::stack_pointer(), height_slot));
    builder.emit(abi::store_u64(&value, &record, IMAGE_HEIGHT));
    builder.emit(abi::load_u64(&value, abi::stack_pointer(), shadow_slot));
    builder.emit(abi::store_u64(&value, &record, IMAGE_PIXELS));
    // Dirty from birth: the backend has never seen these pixels.
    let one = builder.temporary_vreg();
    builder.emit(abi::move_immediate(&one, "Integer", "1"));
    builder.emit(abi::store_u64(&one, &record, IMAGE_DIRTY));
    builder.emit(abi::store_u64(abi::ZERO, &record, IMAGE_LAST_USED_FRAME));

    builder.emit(abi::move_register(RESULT_VALUE_REGISTER, &record));
    builder.emit(abi::move_immediate(
        RESULT_TAG_REGISTER,
        "Integer",
        RESULT_OK_TAG,
    ));
    builder.emit(abi::branch(&done));

    builder.emit(abi::label(&bad_count));
    builder.raise_error_bare("ErrBadPixelCount")?;

    builder.emit(abi::label(&done));
    builder.emit(abi::return_());

    prepend_wrong_mode_gate(
        &mut builder.instructions,
        &mut builder.relocations,
        &symbol,
        ctx.presentation_mode_offset,
        ModeRequirement::Canvas,
    );

    Ok(ValueResult {
        origin: None,
        type_: ParameterType::Nothing,
        location: Operand::from("void"),
        text: "canvas.createImage".to_string(),
    })
}

pub(crate) fn register(pkg: &mut RegistryPackage) {
    pkg.add_function(RegistryFunction {
        name: "createImage",
        intro: INTRO,
        desc: DESC,
        example: EX,
        expected_arguments: None,
        internal_only: false,
        implementations: vec![Implementation {
            params: vec![
                Parameter {
                    name: "width",
                    desc: "The image width in pixels.",
                    aliases: &[],
                    ty: ParameterType::Integer,
                    default: DefaultValue::None,
                },
                Parameter {
                    name: "height",
                    desc: "The image height in pixels.",
                    aliases: &[],
                    ty: ParameterType::Integer,
                    default: DefaultValue::None,
                },
                Parameter {
                    name: "pixels",
                    desc: "RGBA8 bytes in row order, top row first — exactly \
                           `width * height * 4` of them.",
                    aliases: &[],
                    ty: ParameterType::list_of(ParameterType::Byte),
                    default: DefaultValue::None,
                },
            ],
            return_type: ParameterType::named(super::IMAGE_TYPE_ID),
            errors: vec!["ErrBadPixelCount", "ErrOutOfMemory", "ErrWrongMode"],
            body: Body::abi_function(lower_create_image),
        }],
    });
}
