//! The two pinned-Unicode **range tables** — general category and Script — as
//! data the emitted program reads at runtime (plan-118-B).
//!
//! Both properties used to ship as generated MFBASIC: one flat `IF cp <= N THEN
//! RETURN "Lu"` arm per run, 4,099 arms for the category table and 1,708 for the
//! script table, compiled into the program as code. That cost **2,556,471
//! machine instructions — 15.0 % of the whole acceptance-corpus module** (the
//! top three rows of `-vv`'s `largest lower_function` leaderboard), and made
//! every query a linear scan of up to 4,099 compares. The runs are data; this
//! module reads them as data.
//!
//! # Why not the utf8proc trie
//!
//! [`super::runtime_tables`] already ships a two-stage property trie with a
//! general-category field, and reusing it would have cost nothing to emit. It
//! cannot be used, measured 2026-09-01:
//!
//! * The vendored utf8proc carries a **newer UCD** than the pinned Unicode
//!   16.0.0 these tables are generated from. Its categories differ on **4,804
//!   scalars** — 4,803 unassigned (`Cn`) here and assigned there, plus U+0295,
//!   `Ll` here and `Lo` there. Answering `\p{gc}` from it would silently change
//!   4,804 answers.
//! * Its property records are **deduplicated on utf8proc's own field set**, so
//!   19 of the 8,385 rows are shared by scalars whose Unicode 16.0.0 categories
//!   differ (one row is reached by `Cn`, `Ll` *and* `Lo` scalars). A category
//!   field packed into that record could not represent these answers even in
//!   principle.
//!
//! So the pinned answers travel in their own generated artifacts, which also
//! means a utf8proc bump can no longer move them.
//!
//! # Format
//!
//! Each artifact is one line per run, `<last codepoint of the run> <name>`,
//! ascending and contiguous over `0 ..= 0x10FFFF`. A lookup binary-searches for
//! the first run whose end is `>= cp` and takes that run's name. Emitted as two
//! data objects per table: an 8-byte-per-run `(u32 end, u32 name index)` array,
//! and a fixed-stride array of `mfb.string.v1` records holding the names, so the
//! answer is a rodata pointer and the query allocates nothing.

/// `unicode_gencat_ranges.txt`, generated by `scripts/gen_unicode_gencat_table.py`.
const GENCAT_RANGES: &str = include_str!("../codegen/string/unicode/unicode_gencat_ranges.txt");

/// `unicode_script_ranges.txt`, generated by `scripts/gen_unicode_script_table.py`.
const SCRIPT_RANGES: &str = include_str!("../codegen/string/unicode/unicode_script_ranges.txt");

/// One property's runs plus the distinct names they select.
pub(crate) struct RangeTable {
    /// `(last codepoint of the run, index into `names`)`, ascending by codepoint,
    /// contiguous, covering `0 ..= 0x10FFFF`.
    pub(crate) runs: Vec<(u32, u32)>,
    /// The distinct property values, in the order the indices above use.
    pub(crate) names: Vec<&'static str>,
}

impl RangeTable {
    /// The name every emitted `mfb.string.v1` record is padded to, in bytes:
    /// `u64 byteLength` + the bytes + a NUL, rounded up to 8.
    ///
    /// Fixed stride rather than an offset table because it makes the lookup's
    /// last step one multiply — and at 171 script names it costs under 7 KiB.
    pub(crate) fn name_stride(&self) -> usize {
        let longest = self.names.iter().map(|name| name.len()).max().unwrap_or(0);
        (8 + longest + 1).div_ceil(8) * 8
    }

    /// The runs as `(u32 end, u32 name index)` little-endian records.
    pub(crate) fn runs_bytes(&self) -> Vec<u8> {
        let mut bytes = Vec::with_capacity(self.runs.len() * 8);
        for (end, index) in &self.runs {
            bytes.extend_from_slice(&end.to_le_bytes());
            bytes.extend_from_slice(&index.to_le_bytes());
        }
        bytes
    }

    /// The names as consecutive fixed-stride `mfb.string.v1` records, so
    /// `base + index * name_stride()` is a String the program can return.
    pub(crate) fn names_bytes(&self) -> Vec<u8> {
        let stride = self.name_stride();
        let mut bytes = Vec::with_capacity(self.names.len() * stride);
        for name in &self.names {
            let start = bytes.len();
            bytes.extend_from_slice(&(name.len() as u64).to_le_bytes());
            bytes.extend_from_slice(name.as_bytes());
            bytes.push(0);
            bytes.resize(start + stride, 0);
        }
        bytes
    }

    /// [`runs_bytes`](Self::runs_bytes) as the hex string a data object carries.
    pub(crate) fn runs_hex(&self) -> String {
        hex(&self.runs_bytes())
    }

    /// [`names_bytes`](Self::names_bytes) as the hex string a data object carries.
    pub(crate) fn names_hex(&self) -> String {
        hex(&self.names_bytes())
    }

    /// The property value of `codepoint`, by the same binary search
    /// `emit_unicode_range_lookup` emits — the reference implementation of the
    /// emitted algorithm, against the same run/name arrays the program reads.
    ///
    /// Test-only, and load-bearing there: it is what
    /// `every_scalar_matches_the_generated_if_chain` checks all 1,114,112
    /// scalars of both tables against the generated MFBASIC IF-chains these
    /// replace. Without it the tables would be checked only by the handful of
    /// scalars the regex/strings fixtures happen to use.
    #[cfg(test)]
    pub(crate) fn lookup(&self, codepoint: u32) -> &'static str {
        let index = self.runs.partition_point(|(end, _)| *end < codepoint);
        // The tables are contiguous to 0x10FFFF, so only an out-of-range scalar
        // can fall off the end; answer it with the last run, which is the
        // unassigned/no-script value.
        let index = index.min(self.runs.len() - 1);
        self.names[self.runs[index].1 as usize]
    }
}

/// The Unicode 16.0.0 general-category runs (4,099 runs, 30 categories).
pub(crate) fn gencat() -> &'static RangeTable {
    static TABLE: std::sync::OnceLock<RangeTable> = std::sync::OnceLock::new();
    TABLE.get_or_init(|| parse(GENCAT_RANGES, "unicode_gencat_ranges.txt"))
}

/// The Unicode 16.0.0 Script runs (1,708 runs, 171 script names).
pub(crate) fn script() -> &'static RangeTable {
    static TABLE: std::sync::OnceLock<RangeTable> = std::sync::OnceLock::new();
    TABLE.get_or_init(|| parse(SCRIPT_RANGES, "unicode_script_ranges.txt"))
}

fn hex(bytes: &[u8]) -> String {
    let mut output = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        output.push_str(&format!("{byte:02x}"));
    }
    output
}

fn parse(source: &'static str, artifact: &str) -> RangeTable {
    let mut runs = Vec::new();
    let mut names: Vec<&'static str> = Vec::new();
    for line in source.lines() {
        if line.starts_with('#') || line.is_empty() {
            continue;
        }
        let (end, name) = line
            .split_once(' ')
            .unwrap_or_else(|| panic!("{artifact}: malformed run line `{line}`"));
        let end: u32 = end
            .parse()
            .unwrap_or_else(|_| panic!("{artifact}: non-numeric run end in `{line}`"));
        let index = match names.iter().position(|known| *known == name) {
            Some(index) => index,
            None => {
                names.push(name);
                names.len() - 1
            }
        };
        runs.push((end, index as u32));
    }
    assert!(
        runs.last().map(|(end, _)| *end) == Some(0x10FFFF),
        "{artifact}: runs must cover through U+10FFFF"
    );
    assert!(
        runs.windows(2).all(|pair| pair[0].0 < pair[1].0),
        "{artifact}: runs must ascend"
    );
    RangeTable { runs, names }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn gencat_table_shape() {
        let table = gencat();
        assert_eq!(table.runs.len(), 4099);
        assert_eq!(table.names.len(), 30);
        // "Lu" -> 8 (len) + 2 + 1 NUL = 11, rounded to 16.
        assert_eq!(table.name_stride(), 16);
        assert_eq!(table.runs_bytes().len(), 4099 * 8);
        assert_eq!(table.names_bytes().len(), 30 * 16);
    }

    #[test]
    fn script_table_shape() {
        let table = script();
        assert_eq!(table.runs.len(), 1708);
        assert_eq!(table.names.len(), 171);
        assert_eq!(table.runs_bytes().len(), 1708 * 8);
        assert_eq!(table.names_bytes().len(), 171 * table.name_stride());
    }

    /// A name record is a well-formed `mfb.string.v1`: little-endian length,
    /// the bytes, a NUL. The emitted lookup hands this pointer back as a String,
    /// so a wrong length or a missing terminator is a wrong string at runtime.
    #[test]
    fn name_records_are_well_formed_strings() {
        for table in [gencat(), script()] {
            let stride = table.name_stride();
            let bytes = table.names_bytes();
            for (index, name) in table.names.iter().enumerate() {
                let record = &bytes[index * stride..(index + 1) * stride];
                let length = u64::from_le_bytes(record[..8].try_into().expect("8 bytes"));
                assert_eq!(length as usize, name.len(), "length of `{name}`");
                assert_eq!(
                    &record[8..8 + name.len()],
                    name.as_bytes(),
                    "bytes of `{name}`"
                );
                assert_eq!(record[8 + name.len()], 0, "NUL after `{name}`");
            }
        }
    }

    /// Boundary scalars, answered against the pinned tables.
    #[test]
    fn gencat_boundaries() {
        let table = gencat();
        assert_eq!(table.lookup(0), "Cc");
        assert_eq!(table.lookup(0x1F), "Cc");
        assert_eq!(table.lookup(0x20), "Zs");
        assert_eq!(table.lookup(0x41), "Lu");
        assert_eq!(table.lookup(0x61), "Ll");
        assert_eq!(table.lookup(0x30), "Nd");
        // Surrogates are Cs even though `char::from_u32` refuses them.
        assert_eq!(table.lookup(0xD800), "Cs");
        assert_eq!(table.lookup(0xDFFF), "Cs");
        assert_eq!(table.lookup(0x10FFFF), "Cn");
        // U+0295 is Ll in Unicode 16.0.0 and Lo in the vendored utf8proc data:
        // the one scalar that proves this table is not reading the trie.
        assert_eq!(table.lookup(0x295), "Ll");
    }

    /// The binary search answers what a linear scan of the same runs answers,
    /// for **every** scalar `0 ..= 0x10FFFF`, in both tables.
    ///
    /// Two different algorithms over one dataset: a bisection off-by-one at a run
    /// boundary shows up here and essentially nowhere else, because every fixture
    /// that exercises `\p{gc}` or `\p{Script}` touches a handful of scalars and
    /// over a million of them are unassigned. That the runs themselves are the
    /// pinned Unicode 16.0.0 answers is `scripts/check-generated.sh`'s job — it
    /// regenerates both artifacts from `unicodedata` / the vendored UCD and
    /// byte-compares.
    ///
    /// When these tables replaced the generated `unicode_gencat.mfb` /
    /// `unicode_script_of.mfb` IF-chains, the same exhaustive sweep ran against
    /// those files' parsed arms and matched on all 1,114,112 scalars of both
    /// tables. The IF-chains are deleted, so that form of the test went with
    /// them; this is the part that stays checkable.
    #[test]
    fn binary_search_matches_a_linear_scan_for_every_scalar() {
        for table in [gencat(), script()] {
            let mut run = 0;
            for codepoint in 0..=0x10FFFFu32 {
                while table.runs[run].0 < codepoint {
                    run += 1;
                }
                assert_eq!(
                    table.lookup(codepoint),
                    table.names[table.runs[run].1 as usize],
                    "U+{codepoint:04X}"
                );
            }
        }
    }

    #[test]
    fn script_boundaries() {
        let table = script();
        assert_eq!(table.lookup(0), "Common");
        assert_eq!(table.lookup(0x41), "Latin");
        assert_eq!(table.lookup(0x3B1), "Greek");
        assert_eq!(table.lookup(0x410), "Cyrillic");
        assert_eq!(table.lookup(0x10FFFF), "Unknown");
    }
}
