#!/usr/bin/env python3
"""Print the built-in surface the compiler supports by scanning src/builtins/.

Each package is reported once, merging two sources:
  * the Rust builtins (``*.rs``) for the public ``pkg::name`` function/constant
    call surface, and
  * the MFBASIC package implementations (``*.mfb``) for the EXPORTed types.
"""

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
BUILTINS_DIR = REPO_ROOT / "src" / "builtins"
SKIP_FILES = {"mod.rs", "resource.rs"}

# Internal dispatch targets that appear in an `is_<pkg>_call` predicate for the
# runtime plumbing but are not part of the user-callable surface, so they are
# omitted from the documented function list. `tls::closeListener` is the
# listener-shaped body that `tls::close` over a `TlsListener` rewrites to during
# IR lowering (plan-06-tls-server.md §4.1). The `crypto::generateP*Raw` entries
# are the internal raw-key generators backing the public `generateP*` wrappers.
INTERNAL_CALLS = {
    "tls::closeListener",
    "crypto::generateP256Raw",
    "crypto::generateP384Raw",
    "crypto::generateP521Raw",
}

# FUNC/SUB/TYPE declarations in MFBASIC package sources, e.g.
#   EXPORT TYPE Instant
#   FUNC __datetime_now AS Instant
#   FUNC __collections_sort OF T(value AS List OF T) AS List OF T
DECL_RE = re.compile(
    r"^\s*(EXPORT\s+)?(FUNC|SUB|TYPE)\s+([A-Za-z_][A-Za-z0-9_]*)",
    re.MULTILINE,
)


def build_const_map(src: str) -> dict[str, str]:
    """Map Rust identifier → string value for const X: &str = "..." declarations."""
    return {
        m.group(1): m.group(2)
        for m in re.finditer(
            r"^\s*(?:pub(?:\([^)]*\))?\s+)?const\s+([A-Z][A-Z0-9_]*)\s*:\s*&str\s*=\s*\"([^\"]+)\"\s*;",
            src,
            re.MULTILINE,
        )
    }


def slice_const_members(src: str, name: str, package: str) -> list[str]:
    """Bare member names from a `const NAME: &[&str] = &["a", "b"];` slice.

    `collections` names its surface this way rather than as one `&str` const per
    call, so `build_const_map` cannot see it and all 39 members were invisible to
    this script — which is why `update_man.sh collections` failed outright
    (bug-336-S2). Returns fully-qualified `package.member` names to match the
    shape `resolve()` produces.
    """
    m = re.search(
        rf"^\s*(?:pub(?:\([^)]*\))?\s+)?const\s+{re.escape(name)}\s*:\s*&\[&str\]\s*=\s*&\[(.*?)\];",
        src,
        re.MULTILINE | re.DOTALL,
    )
    if not m:
        return []
    return [f"{package}.{member}" for member in re.findall(r'"([^"]+)"', m.group(1))]


def idents_in_fn(src: str, fn_name: str) -> list[str]:
    """Extract uppercase Rust identifiers from the body of the named function."""
    fn_re = re.compile(
        rf"\bfn\s+{re.escape(fn_name)}\s*\([^)]*\)[^{{]*\{{",
        re.DOTALL,
    )
    m = fn_re.search(src)
    if not m:
        return []
    start = m.end()
    depth = 1
    i = start
    while i < len(src) and depth > 0:
        c = src[i]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
        i += 1
    body = src[start : i - 1]
    return re.findall(r"\b([A-Z][A-Z0-9_]*)\b", body)


def resolve(idents: list[str], const_map: dict[str, str]) -> list[str]:
    """Resolve Rust identifier names to their string values, preserving order, deduped."""
    seen: set[str] = set()
    result = []
    for ident in idents:
        val = const_map.get(ident)
        if val and val not in seen:
            seen.add(val)
            result.append(val)
    return result


def package_decls(src: str) -> list[tuple[str, str, bool]]:
    """Extract (kind, name, exported) for FUNC/SUB/TYPE in an MFBASIC source."""
    decls = []
    for m in DECL_RE.finditer(src):
        exported = bool(m.group(1))
        kind = m.group(2)
        name = m.group(3)
        decls.append((kind, name, exported))
    return decls


def package_label(stem: str) -> str:
    """Map an MFBASIC source stem to its package name (`http_package` → `http`)."""
    if stem.endswith("_package"):
        return stem[: -len("_package")]
    if stem == "regex_unicode":
        return "regex"
    # The Rust module is `errorcode.rs`; the package users import is `errorCode`.
    if stem == "errorcode":
        return "errorCode"
    return stem


def errorcode_members() -> list[str]:
    """The `errorCode::Err*` constant names.

    `errorCode` has no `is_*_call` predicate and no `&str` consts to scan: its
    surface is a build-time table generated by `build.rs` from the spec's Constant
    Registry, so this reads the same source the generator does (bug-336-S2/S4).
    """
    doc = REPO_ROOT / "src/docs/spec/diagnostics/02_error-codes.md"
    if not doc.exists():
        return []
    names: list[str] = []
    in_section = False
    for line in doc.read_text().splitlines():
        if line.startswith("## "):
            in_section = "Constant Registry" in line
            continue
        if not in_section or not line.lstrip().startswith("| `"):
            continue
        cells = [c.strip() for c in line.split("|")]
        if len(cells) < 4:
            continue
        name = cells[3].strip("`")
        if name.startswith("Err"):
            names.append(name)
    return names


def collect_packages() -> dict[str, dict[str, list[str]]]:
    """Build {label: {"functions", "constants", "types"}} across .rs and .mfb."""
    packages: dict[str, dict[str, list[str]]] = {}

    def bucket(label: str) -> dict[str, list[str]]:
        return packages.setdefault(
            label, {"functions": [], "constants": [], "types": []}
        )

    # Public call surface from the Rust builtins.
    for path in sorted(BUILTINS_DIR.glob("*.rs")):
        if path.name in SKIP_FILES:
            continue
        src = path.read_text()
        const_map = build_const_map(src)
        # `errorcode.rs` declares no `&str` consts at all — its surface is a
        # build-time table — so it must not be skipped here (bug-336-S2/S4).
        if not const_map and path.stem != "errorcode":
            continue

        stem = path.stem
        label = package_label(stem)
        # The public call surface is the set of name-constants matched by the
        # package's call predicate. Most packages list them directly in
        # `is_<pkg>_call`; some (e.g. vector) delegate to an `is_<pkg>_function`
        # helper, so scan both predicates and merge (resolve() dedupes).
        call_idents = [
            ident
            # `is_<pkg>_call` is the usual predicate; some packages delegate to an
            # `is_<pkg>_function` helper (vector), and `testing` is the one module
            # using a private naming convention — its predicate is `is_expect_call`
            # (bug-336-S2). Scanning all three and merging is safe: resolve() dedupes
            # and a name that is not a const simply does not resolve.
            for fn in (
                f"is_{stem}_call",
                f"is_{stem}_function",
                # `testing`'s predicate is `is_expect_call`, which delegates the
                # typed assertions to two helpers.
                "is_expect_call",
                "is_equality_assert",
                "is_inequality_assert",
            )
            for ident in idents_in_fn(src, fn)
        ]
        raw = resolve(call_idents, const_map)
        # Packages that name their surface as a `&[&str]` slice rather than as one
        # const per call.
        for slice_name in ("FUNCTIONS", "NATIVE_MEMBERS"):
            raw.extend(slice_const_members(src, slice_name, stem))
        # `errorCode` exports constants, not calls: its predicate is
        # `is_errorcode_constant` over a build-time-generated table.
        errorcode_constants = (
            [f"errorCode::{name}" for name in errorcode_members()] if stem == "errorcode" else []
        )
        functions = [
            n.replace(".", "::")
            for n in raw
            if n.replace(".", "::") not in INTERNAL_CALLS
        ]
        constants = (
            [n.replace(".", "::") for n in resolve(idents_in_fn(src, "is_math_constant"), const_map)]
            if stem == "math"
            else errorcode_constants
        )
        if functions or constants:
            b = bucket(label)
            b["functions"].extend(functions)
            b["constants"].extend(constants)

    # Record types declared in RUST rather than in an MFBASIC package source.
    # `builtin_type_fields` is the authority: a type with fields is a record a
    # user can read, so it belongs on the package's `types` page. Scanning only
    # `*_package.mfb` for `EXPORT TYPE` (below) made these structurally
    # invisible to the type-page loop no matter how often it ran, which is why
    # `net`'s fields ended up as prose in its package page and `term`'s two
    # records were hoisted into the global `types` pseudo-package (bug-336-S7).
    # Opaque resource handles have no fields and correctly do not appear.
    for path in sorted(BUILTINS_DIR.glob("*.rs")):
        if path.name in SKIP_FILES:
            continue
        src = path.read_text()
        const_map = build_const_map(src)
        label = package_label(path.stem)
        body = idents_in_fn(src, "builtin_type_fields")
        for name in resolve(body, const_map):
            # These consts hold a BARE type name (`Address`, `TermColor`), unlike
            # the call consts which are already `pkg.call`.
            qualified = name if "." in name else f"{label}.{name}"
            entry = qualified.replace(".", "::")
            if entry not in bucket(label)["types"]:
                bucket(label)["types"].append(entry)

    # Exported types from the MFBASIC package implementations. The `__pkg_*`
    # helper FUNCs are internal — the public function surface comes from the
    # Rust scan above — so only EXPORTed declarations are listed here.
    for path in sorted(BUILTINS_DIR.glob("*.mfb")):
        label = package_label(path.stem)
        for kind, name, exported in package_decls(path.read_text()):
            if exported and kind == "TYPE":
                entry = f"{label}::{name}"
                if entry not in bucket(label)["types"]:
                    bucket(label)["types"].append(entry)

    return packages


def main() -> None:
    packages = collect_packages()
    if not packages:
        print(f"No builtin source files found under {BUILTINS_DIR}", file=sys.stderr)
        sys.exit(1)

    total_fns = total_consts = total_types = 0

    for label in sorted(packages):
        b = packages[label]
        print(f"\n[{label}]")
        for name in b["functions"]:
            print(f"  {name}  (function)")
        for name in b["constants"]:
            print(f"  {name}  (constant)")
        for name in b["types"]:
            print(f"  {name}  (type)")

        total_fns += len(b["functions"])
        total_consts += len(b["constants"])
        total_types += len(b["types"])

    print(
        f"\nTotal: {total_fns} functions, {total_consts} constants, {total_types} types"
    )


if __name__ == "__main__":
    main()
