#!/usr/bin/env bash
# Authoring rules shared by scripts/update_man.sh and scripts/update_man_package.sh.
#
# These two drivers used to carry the same prose twice — 19 byte-identical lines,
# the Provenance paragraph three times, the renderer-subset list three times, and
# the Errors-table block twice. A rule fixed in one stayed broken in the others,
# and they had drifted: `update_man.sh` told the authoring agent to read
# `src/builtins/<pkg>.rs` and never mentioned `src/builtins/<pkg>_package.mfb`,
# while `update_man_package.sh` correctly added it. For the 13 packages
# implemented in MFBASIC the `.rs` is a registration shim — an agent following the
# first instruction literally documents the shim (bug-336-S11).
#
# `AGENTS.md` designates these driver scripts as the authoritative home for the
# authoring rules, so this file is that home; the templates in `.ai/` stay bare
# skeletons.
#
# Usage: source this file, then interpolate the variables into the prompt.

# Where a package's compiler source lives. Echoes a comma-separated list.
# For a package implemented in MFBASIC the `.mfb` is where the real signatures,
# defaults, and error paths are; the `.rs` carries name constants, the
# `is_*_call` predicate, return-type tables, and `call_param_names`. Both matter.
man_package_sources() {
  local pkg="$1"
  local sources=()
  case "$pkg" in
    errorCode|errorcode)
      # No `is_*_call` predicate and no `&str` consts: the constant table is
      # generated by build.rs from the specification.
      sources+=("src/builtins/errorcode.rs")
      sources+=("src/docs/spec/diagnostics/02_error-codes.md")
      ;;
    *)
      [[ -f "src/builtins/${pkg}.rs" ]] && sources+=("src/builtins/${pkg}.rs")
      [[ -f "src/builtins/${pkg}_package.mfb" ]] && sources+=("src/builtins/${pkg}_package.mfb")
      ;;
  esac
  if [[ ${#sources[@]} -eq 0 ]]; then
    echo "(no dedicated source file; infer the package from its function man pages)"
  else
    local list
    list="$(printf '%s, ' "${sources[@]}")"
    echo "${list%, }"
  fi
}

# The Markdown subset the terminal renderer supports.
MAN_RULE_RENDERER='- Use the renderer'"'"'s supported Markdown subset only: ATX headings, paragraphs,
  bullet/ordered lists, fenced code blocks, pipe tables, and inline
  `code`/**bold**/*italic*/[links](url). Wrap identifiers and types in `code`.'

# How to cite an implementation claim.
MAN_RULE_PROVENANCE='- Provenance: back a non-obvious implementation claim (error code, arity, numeric
  range/bound, magic number, offset, enum variant, field type, units) with an
  invisible `[[src/file.rs:Symbol]]` citation at claim-cluster granularity —
  symbol-preferred, `[[src/file.rs:line]]` only where no symbol fits.
  GREP-CONFIRM the symbol exists in that exact file before citing it: this is
  enforced by `cargo test man_citations_resolve`, which fails the build on a
  citation naming a file or symbol that is not there. The renderer strips
  `[[ ]]` everywhere (including headings), so they never display in `mfb man`
  output but keep claims traceable for reviewers. Do not add non-verifiable
  claims.'

# The Errors table, required on every page.
MAN_RULE_ERRORS='Errors table (required, always present):
- List every error the subject can itself raise, one row per error, with the
  numeric code, the symbolic name, and the condition:

    ## Errors

    | Code | Name | Raised when |
    | --- | --- | --- |
    | `77050002` | `ErrInvalidArgument` | <condition> |
    | `77050001` | `ErrIndexOutOfRange` | <condition> |

- Use the exact code<->name pairs from src/target/shared/code/error_constants.rs.
  Do not invent codes or names.
- If it cannot itself raise any error, replace the table with a single line that
  reads exactly: No errors.
  (Errors propagating from evaluating arguments before the call do not count as
  errors this function raises; do not list them.)'

# Why the existing page is not evidence.
MAN_RULE_CORRECTNESS='Correctness:
- Existing man page content must NOT be trusted as correct. Verify every claim
  against the actual compiler code before restating it.
- A page that reads well but states something the compiler does not do is worse
  than no page. This has happened repeatedly: pages documenting a function with
  no implementation at all, parameter names that are reserved words and so fail
  to PARSE when used, and an error code belonging to a different error entirely.
- Key to this whole process is that the information in the man pages is valid
  and correct.'
