#!/usr/bin/env python3
"""Generate the malicious `.mfp` for the PKG-04 security fixture (pkg-04-type-cycle).

Builds this benign base package with `mfb`, applies the `mutate_cyclic_type` byte-level
mutation from ../mfp_craft.py, and writes the result into the consumer fixture
at tests/syntax/security/pkg-04-type-cycle/packages/sec_cyclic.mfp. Run it after changing the source or
the container format:

    python3 tools/security-package-sources/pkg-04-type-cycle/generate.py [path/to/mfb]

The generated bytes are committed; this script exists for reproducibility.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))
import mfp_craft as m

REPO = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
MFB = sys.argv[1] if len(sys.argv) > 1 else os.path.join(REPO, "target", "debug", "mfb")
FIXTURE = os.path.join(REPO, "tests", "syntax", "security", "pkg-04-type-cycle")

base = m.build_base_package(HERE, MFB)
malicious = m.mutate_cyclic_type(base)
m.write_fixture_package(FIXTURE, "sec_cyclic", malicious)
